Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-08, with the labels that each got.

#3743 feat: MET-2276 Fetch and index data reference by anchor link
  src/components/Overview/TabOverview/index.tsx
  src/types/governanceOverview.d.ts
Labels: 1.7.0

#3732 Feat/met 2245 number of transactions per day
  src/components/NetworkMonitoring/TransactionNumberChart/index.tsx
  src/components/NetworkMonitoring/TransactionNumberChart/styles.ts
  src/components/NetworkMonitoring/index.tsx
Labels: 1.7.0

#3747 feat/met 2101 governance action details
  src/commons/resources/icons/gov-body-icon.svg
  src/commons/resources/index.ts
  src/components/GovernanceActionDetails/CreatedBy/index.tsx
  src/components/GovernanceActionDetails/Description/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/VoteSubmitted/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/styles.ts
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/components/GovernanceActionDetails/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3748 fix: update code
  src/commons/utils/constants.ts
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/styles.ts
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3749 feat/met 2101 governance action details
  src/components/GovernanceActionDetails/CreatedBy/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/VoteSubmitted/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/styles.ts
  src/types/governanceOverview.d.ts
Labels: dev-test

#3750 fix: update coding
  src/components/GovernanceActionDetails/OverviewHeader/VoteSubmitted/index.tsx
Labels: dev-test

#3752 fix: update coding
  src/commons/resources/icons/description-icon.svg
  src/commons/resources/icons/govBody-icon.svg
  src/commons/resources/icons/govID-icon.svg
  src/commons/resources/icons/timeStamp-icon.svg
  src/commons/resources/index.ts
  src/components/GovernanceActionDetails/CreatedBy/index.tsx
  src/components/GovernanceActionDetails/Description/styles.ts
  src/components/GovernanceActionDetails/OverviewHeader/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/styles.ts
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/index.tsx
  src/components/GovernanceActionDetails/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3755 fix: update coding
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3758 fix: update coding
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
Labels: dev-test

#3759 fix: update coding
  src/components/GovernanceActionDetails/OverviewHeader/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/index.tsx
Labels: dev-test

#3760 fix: update coding
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/index.tsx
Labels: dev-test

#3726 fix: scroll tab stake address history
  src/components/StakeDetail/StakeTab/Tabs/StakeHistoryTab.tsx
Labels: 1.7.0

#3720 fix: popup address sc detail
  src/pages/SmartContractDetail/ViewAddressesModal.tsx
Labels: 1.7.0

#3761 fix: update coding
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3764 fix: MET-2245 update chart in dashboard
  src/components/Home/Trending/TransactionChart/index.tsx
  src/components/Home/Trending/TransactionChart/styles.ts
  src/components/NetworkMonitoring/TransactionNumberChart/index.tsx
Labels: dev-test

#3762 feat/met 2101 governance action details
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/resources/icons/action-icon.svg
  src/commons/resources/icons/date-icon.svg
  src/commons/resources/icons/description-icon.svg
  src/commons/resources/icons/feedbackIcon-icon.svg
  src/commons/resources/icons/gov-body-icon.svg
  src/commons/resources/icons/govBody-icon.svg
  src/commons/resources/icons/govID-icon.svg
  src/commons/resources/icons/pencil-icon.svg
  src/commons/resources/icons/timeStamp-icon.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/commons/utils/constants.ts
  src/components/GovernanceActionDetails/CreatedBy/index.tsx
  src/components/GovernanceActionDetails/Description/index.tsx
  src/components/GovernanceActionDetails/Description/styles.ts
  src/components/GovernanceActionDetails/OverviewHeader/VoteSubmitted/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/styles.ts
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/CardVotesOverview/styles.ts
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/styles.ts
  src/components/GovernanceActionDetails/VotesOverview/index.tsx
  src/components/GovernanceActionDetails/index.tsx
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/Overview/TabOverview/index.tsx
  src/locales/en/translation.json
  src/pages/GovernanceActionDetails/index.tsx
  src/pages/GovernanceActionDetails/styles.ts
  src/types/governanceOverview.d.ts
Labels: 1.7.0

#3766 feat: MET-2247-update-chart
  src/components/NetworkMonitoring/BlockPropagation/index.tsx
Labels: 1.7.0

#3768 fix: input dot in participation rate
  src/components/Dreps/DrepFilter/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3769 fix: data more than 6 decimal places after the decimal point
  src/commons/utils/helper.ts
  src/components/Dreps/DrepFilter/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/pages/GovernanceActionDetails/index.tsx
Labels: dev-test

#3763 fix: MET-2245 update chart in dashboard
  src/components/Home/Trending/TransactionChart/index.tsx
  src/components/Home/Trending/TransactionChart/styles.ts
  src/components/NetworkMonitoring/TransactionNumberChart/index.tsx
Labels: 1.7.0

#3771 fix: update coding
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
Labels: dev-test

#3773 fix: remove event click in piechart
  src/components/Overview/ChartOverview/index.tsx
Labels: dev-test

#3774 fix: cannot enter decimals
  src/components/Dreps/DrepFilter/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3772 Fix/remove event click pie chart
  src/components/Overview/ChartOverview/index.tsx
Labels: 1.7.0

#3756 fix: icon ada epoch details
  src/components/EpochDetail/EpochOverview/index.tsx
  src/components/EpochDetail/EpochOverview/styles.ts
Labels: 1.7.0

#3753 fix: input dot in participation rate
  src/components/Dreps/DrepFilter/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: 1.7.0

#3711 Merge 1.6.0 into main
  src/pages/NativeScriptsAndSC/Card.tsx
Labels: 1.6.0

#3780 fix: remove event click in piechart
  src/components/GovernanceActionDetails/OverviewHeader/index.tsx
  src/components/Overview/ChartOverview/index.tsx
Labels: dev-test

#3785 Fix/conflict 1 8 dev test
  .github/workflows/publish.yaml
  src/components/Dreps/DrepsList/index.tsx
Labels: conflict, dev-test

#3796 Feat/met 2250 merge test
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3800 Fix/bolnisi test
  docker-compose.yml
  src/commons/animation/motion-div.tsx
  src/commons/hooks/useInView.ts
  src/commons/resources/bolnisiLanding/background-header-light.png
  src/components/commons/Layout/index.tsx
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3801 fix: MET-2250 update animation
  src/commons/animation/motion-div.tsx
  src/commons/animation/motion-img.tsx
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3802 fix: bg dashboard
  src/components/commons/Layout/index.tsx
Labels: dev-test

#3804 fix: bug ui dreps
  src/components/Dreps/DrepsList/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3783 fix: anchor link dreps list
  src/components/Dreps/DrepsList/index.tsx
Labels: 1.8.0

#3806 fix: hyperlink dreps details
  src/components/Dreps/DrepsList/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3807 feat: MET-2250 add dark mode
  src/commons/resources/bolnisiLanding/background-header-dark.png
  src/components/commons/Layout/index.tsx
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3808 feat: MET-2250 update ui
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3809 feat: MET-2250 update title
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3788 feat: MET-2300 upgrade reactjs 18.3.1
  package-lock.json
  package.json
Labels: dev-test

#3811 feat: MET-2301 upgrade MUI
  package-lock.json
  package.json
Labels: dev-test

#3812 Fix/met 2049 error status 504
  src/components/ConstitutionalCommitteeDetail/index.tsx
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/index.tsx
  src/components/commons/Table/index.tsx
  src/pages/NativeScriptsAndSC/TabNativeScripts.tsx
  src/pages/NativeScriptsAndSC/TabSmartContracts.tsx
Labels: dev-test

#3814 feat: MET-2250 update code
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3817 fix: MET-2049 status error 504
  src/components/GovernanceVotes/index.tsx
  src/components/NetworkMonitoring/BlockPropagation/index.tsx
  src/components/NetworkMonitoring/RegisteredStakepools/index.tsx
  src/components/NetworkMonitoring/TransactionNumberChart/index.tsx
  src/components/Overview/index.tsx
  src/pages/DelegatorLifecycle/index.tsx
  src/pages/Epoch/index.tsx
  src/pages/ProtocolParameter/index.tsx
  src/pages/SPOLifecycle/index.tsx
Labels: dev-test

#3818 fix: hyperlink drep details
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3822 fix: native script detail
  src/components/NativeScriptsDetail/Tabs/MinttingBurningPolicy.tsx
Labels: dev-test

#3787 feat: MET-2300 upgrade reactjs 18.3.1
  package-lock.json
  package.json
Labels: 1.8.0

#3810 feat: MET-2301 upgrade MUI
  package-lock.json
  package.json
Labels: 1.8.0

#3825 fix: MET-2049 status error 504
  src/components/GovernanceActionDetails/CreatedBy/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/index.tsx
  src/components/NativeScriptsDetail/Tabs/AssociatedAddress.tsx
  src/components/NativeScriptsDetail/Tabs/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Deregistration/RecentDeregistration/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Registration/RecentRegistrations/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Withdraw/RecentWithdraws/index.tsx
  src/pages/AddressWalletDetail/index.tsx
  src/pages/BlockDetail/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/EpochDetail/index.tsx
  src/pages/StakeDetail/index.tsx
  src/pages/TokenDetail/index.tsx
  src/pages/TransactionDetail/index.tsx
Labels: dev-test

#3826 fix: MET-2049 status error 504
  src/components/Home/TopDelegationPools/index.tsx
Labels: dev-test

#3819 fix: console error
  src/commons/utils/helper.ts
  src/components/ConstitutionalCommittees/Overrall/index.tsx
  src/components/ConstitutionalCommittees/Overrall/styles.tsx
  src/components/DelegationPool/DelegationOverview/index.tsx
  src/components/DelegationPool/DelegationOverview/styles.ts
  src/components/Dreps/DrepsOverview/index.tsx
  src/components/Dreps/DrepsOverview/styles.ts
  src/components/Home/Statistic/index.tsx
  src/components/Home/Statistic/style.ts
  src/components/Home/Trending/TransactionChart/index.tsx
  src/components/NativeScriptsDetail/Tabs/styles.ts
  src/components/NetworkMonitoring/TransactionNumberChart/index.tsx
  src/components/commons/CustomAccordion/styles.ts
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailHeader/styles.ts
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/components/commons/Layout/Sidebar/FooterMenu/index.tsx
  src/components/commons/RateWithIcon/index.tsx
  src/components/commons/Table/styles.ts
  src/pages/Epoch/index.tsx
  src/pages/NativeScriptsAndSC/Tabs.tsx
  src/pages/NativeScriptsAndSC/styles.ts
Labels: dev-test

#3827 fix: update txHash
  src/pages/BolnisiLanding/index.tsx
Labels: 1.8.0

#3828 Fix/resolve conflict
  package-lock.json
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3831 fix: update type:
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3830 fix: remove warning
  src/components/TokenDetail/TokenAnalytics/index.tsx
  vite.config.ts
Labels: dev-test

#3813 fix: MET-2049 error status 504
  src/components/ConstitutionalCommitteeDetail/index.tsx
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/index.tsx
  src/components/GovernanceActionDetails/CreatedBy/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/Home/TopDelegationPools/index.tsx
  src/components/NativeScriptsDetail/Tabs/AssociatedAddress.tsx
  src/components/NativeScriptsDetail/Tabs/index.tsx
  src/components/NetworkMonitoring/BlockPropagation/index.tsx
  src/components/NetworkMonitoring/RegisteredStakepools/index.tsx
  src/components/NetworkMonitoring/TransactionNumberChart/index.tsx
  src/components/Overview/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Deregistration/RecentDeregistration/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Registration/RecentRegistrations/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Withdraw/RecentWithdraws/index.tsx
  src/components/commons/Table/index.tsx
  src/pages/AddressWalletDetail/index.tsx
  src/pages/BlockDetail/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/DelegatorLifecycle/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/Epoch/index.tsx
  src/pages/EpochDetail/index.tsx
  src/pages/NativeScriptsAndSC/TabNativeScripts.tsx
  src/pages/NativeScriptsAndSC/TabSmartContracts.tsx
  src/pages/ProtocolParameter/index.tsx
  src/pages/SPOLifecycle/index.tsx
  src/pages/StakeDetail/index.tsx
  src/pages/TokenDetail/index.tsx
  src/pages/TransactionDetail/index.tsx
Labels: 1.8.0

#3829 fix/met 2303 console errors
  src/commons/utils/helper.ts
  src/components/ConstitutionalCommittees/Overrall/index.tsx
  src/components/ConstitutionalCommittees/Overrall/styles.tsx
  src/components/DelegationPool/DelegationOverview/index.tsx
  src/components/DelegationPool/DelegationOverview/styles.ts
  src/components/Dreps/DrepsOverview/index.tsx
  src/components/Dreps/DrepsOverview/styles.ts
  src/components/Home/Statistic/index.tsx
  src/components/Home/Statistic/style.ts
  src/components/Home/Trending/TransactionChart/index.tsx
  src/components/NativeScriptsDetail/Tabs/styles.ts
  src/components/NetworkMonitoring/TransactionNumberChart/index.tsx
  src/components/TokenDetail/TokenAnalytics/index.tsx
  src/components/commons/CustomAccordion/styles.ts
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailHeader/styles.ts
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/components/commons/Layout/Sidebar/FooterMenu/index.tsx
  src/components/commons/RateWithIcon/index.tsx
  src/components/commons/Table/styles.ts
  src/pages/Epoch/index.tsx
  src/pages/NativeScriptsAndSC/Tabs.tsx
  src/pages/NativeScriptsAndSC/styles.ts
  vite.config.ts
Labels: 1.8.0

#3770 fix: data more than 6 decimal places after the decimal point
  src/commons/utils/helper.ts
  src/components/Dreps/DrepFilter/index.tsx
  src/components/GovernanceActionDetails/OverviewHeader/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/components/Overview/ChartOverview/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/locales/en/translation.json
  src/pages/GovernanceActionDetails/index.tsx
Labels: 1.8.0

#3805 Fix/bug UI dreps
  src/components/Dreps/DrepsList/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.8.0

#3821 fix: native script detail
  src/components/NativeScriptsDetail/Tabs/MinttingBurningPolicy.tsx
Labels: 1.8.0

#3843 Fix/display missing boder top test
  src/components/GovernanceVotes/index.tsx
  src/components/StakeDetail/StakeTab/index.tsx
  src/components/TabularView/StakeTab/index.tsx
  src/components/TransactionDetail/TransactionMetadata/index.tsx
  src/components/commons/CustomAccordion/index.tsx
  src/components/commons/CustomAccordion/styles.ts
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/SmartContractDetail/ContractTabs.tsx
Labels: dev-test

#3838 fix: governance overview bug ui
  src/components/Overview/TabOverview/index.tsx
Labels: dev-test
