Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-09, with the labels that each got.

#3789 test: create automation test page top ADA holders
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/api/call-koios/koios.api.ts
  playwright/api/dtos/topADAHolders.dto.ts
  playwright/helpers/endpoints.ts
  playwright/pages/top-ADA-holders.page.ts
  playwright/tests/e2e/features/top-ADA-holders.feature
  playwright/tests/e2e/steps/top-ADA-holders.step.ts
  src/components/TopAddresses/ByADABalance/index.tsx
  src/components/TopAddresses/ByAmountStaked/index.tsx
Labels: Automation Test

#3845 fix: tooltip display not in the middle
  src/components/Overview/TabOverview/index.tsx
Labels: dev-test

#3847 Fix/transaction list bug UI
  src/components/TransactionLists/index.tsx
Labels: dev-test

#3837 fix: governance overview bug ui
  src/components/Overview/TabOverview/index.tsx
Labels: 1.8.0

#3839 fix: display missing border top
  src/components/StakeDetail/StakeTab/index.tsx
  src/components/TabularView/StakeTab/index.tsx
  src/components/TransactionDetail/TransactionMetadata/index.tsx
  src/components/commons/CustomAccordion/index.tsx
  src/components/commons/CustomAccordion/styles.ts
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/SmartContractDetail/ContractTabs.tsx
Labels: 1.8.0

#3846 fix: display table header text not inline
  src/components/TransactionLists/index.tsx
Labels: 1.8.0

#3848 1.8.0
  src/components/Overview/TabOverview/index.tsx
  src/components/StakeDetail/StakeTab/index.tsx
  src/components/TabularView/StakeTab/index.tsx
  src/components/TransactionDetail/TransactionMetadata/index.tsx
  src/components/TransactionLists/index.tsx
  src/components/commons/CustomAccordion/index.tsx
  src/components/commons/CustomAccordion/styles.ts
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/SmartContractDetail/ContractTabs.tsx
Labels: 1.9.0

#3790 test: MET-2298 Create automation test for native token
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/api/dtos/blockfrostNativeTokenInformation.dto.ts
  playwright/helpers/endpoints.ts
  playwright/pages/native-token.page.ts
  playwright/pages/script-detail.page.ts
  playwright/pages/token-detail.page.ts
  playwright/tests/e2e/features/native-token.feature
  playwright/tests/e2e/steps/native-token.steps.ts
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
  src/components/commons/DetailView/DetailViewToken.tsx
  src/pages/Token/index.tsx
Labels: Automation Test

#3852 Feat/met 2257 micar mandatory test
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/resources/icons/Earch.svg
  src/commons/resources/icons/Lighning.svg
  src/commons/resources/icons/clock-white.svg
  src/commons/resources/icons/clock.svg
  src/commons/resources/icons/earch-white.svg
  src/commons/resources/icons/lighning-white.svg
  src/commons/resources/icons/tree-white.svg
  src/commons/resources/icons/tree.svg
  src/commons/resources/icons/wash.svg
  src/commons/resources/icons/waste-white.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/locales/en/translation.json
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarChart/styled.ts
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
  src/pages/Micar/MicarIndicator/index.tsx
  src/pages/Micar/MicarIndicator/styles.ts
  src/pages/Micar/index.tsx
  src/pages/Micar/styles.ts
  vite.config.ts
Labels: dev-test

#3849 Feat/met 2257 word map micar page
  package-lock.json
  package.json
  src/commons/resources/icons/find-location-icon.svg
  src/commons/resources/icons/zoom-in-icon.svg
  src/commons/resources/icons/zoom-out-icon.svg
  src/commons/resources/index.ts
  src/locales/en/translation.json
  src/pages/Micar/MicarIndicator/MapMicar/Resource/topCities.ts
  src/pages/Micar/MicarIndicator/MapMicar/index.tsx
  src/pages/Micar/MicarIndicator/MapMicar/mockData.ts
  src/pages/Micar/MicarIndicator/MapMicar/styles.ts
  src/pages/Micar/MicarIndicator/MapMicar/type.ts
  src/pages/Micar/index.tsx
  src/pages/Micar/styles.ts
Labels: dev-test

#3857 feat: MET-2260 intergration api
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/locales/en/translation.json
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
  src/pages/Micar/MicarIndicator/index.tsx
  src/pages/Micar/index.tsx
  vite.config.ts
Labels: dev-test

#3862 Feat/met 2259 micar emission test
  package-lock.json
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
  src/pages/Micar/index.tsx
Labels: dev-test

#3863 feat: MET-2323 explainer for shield
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/locales/en/translation.json
Labels: dev-test

#3865 fix/MET-2257 world map
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarIndicator/MapMicar/index.tsx
  src/pages/Micar/MicarIndicator/MapMicar/mockData.ts
  src/pages/Micar/MicarIndicator/MapMicar/styles.ts
  src/pages/Micar/styles.ts
Labels: dev-test

#3867 Fix/met 2327 merge test
  package-lock.json
  src/commons/utils/constants.ts
  src/pages/BolnisiLanding/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
Labels: dev-test

#3869 Feat/met 2257 micar indicator test
  src/commons/menus.ts
  src/commons/resources/icons/micar.svg
  src/commons/resources/icons/votes.svg
  src/commons/resources/index.ts
  src/components/commons/Layout/Header/index.tsx
  src/components/commons/Layout/index.tsx
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarChart/styled.ts
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
Labels: dev-test

#3870 fix: MET-2327 update cert
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3871 fix: MET-1667 improve search
  src/components/StakingLifeCycleSearch/index.tsx
  src/components/StakingLifeCycleSearch/styles.ts
Labels: dev-test

#3868 Feat/met 1836 bolnisi display certificate
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/components/TransactionDetail/TransactionMetadata/Metadata/BolnisiWineDrawerConformity.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/index.tsx
  src/types/transactions.d.ts
Labels: dev-test

#3872 fix: MET-1667 improve search
  src/components/StakingLifeCycleSearch/index.tsx
Labels: dev-test

#3873 fix: MET-1667 improve search
  src/components/StakingLifeCycleSearch/index.tsx
Labels: dev-test

#3875 fix: replace domain ipfs
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/GovernanceVotes/OverviewVote.tsx
Labels: dev-test

#3876 Feat/met 2257 micar emission indicartor test
  src/commons/utils/api.ts
  src/locales/en/translation.json
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarChart/styled.ts
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
  src/pages/Micar/MicarIndicator/index.tsx
  src/pages/Micar/MicarIndicator/styles.ts
  src/pages/Micar/index.tsx
Labels: dev-test

#3877 fix: update API
  src/commons/utils/api.ts
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/index.tsx
Labels: dev-test

#3880 fix: bug ui anchor hash in dreps
  src/components/Dreps/DrepsList/index.tsx
Labels: dev-test

#3881 feat/met 1836 bolnisi display certificate
  src/commons/resources/icons/revoked-icon.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/components/TransactionDetail/TransactionMetadata/Metadata/BolnisiWineDrawerConformity.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/index.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/styles.ts
  src/types/transactions.d.ts
Labels: dev-test

#3884 fix: color text
  src/pages/Micar/MicarIndicator/MapMicar/index.tsx
  src/pages/Micar/styles.ts
Labels: dev-test

#3864 feat: MET-2323 explainer for shield
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/locales/en/translation.json
Labels: 1.9.0

#3885 fix: bug ui micar
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarIndicator/styles.ts
  src/pages/Micar/index.tsx
Labels: dev-test

#3886 feat/met 1836 bolnisi display certificate
  src/commons/resources/icons/avatar-icon.svg
  src/commons/resources/index.ts
  src/components/TransactionDetail/TransactionMetadata/Metadata/BolnisiWineDrawerConformity.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/index.tsx
Labels: dev-test

#3887 Feat/met 2257 micar indicartor test
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarIndicator/index.tsx
Labels: dev-test

#3888 fix: update UI micar
  src/commons/resources/icons/search-icon.svg
  src/commons/resources/index.ts
  src/locales/en/translation.json
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
  src/pages/Micar/MicarIndicator/index.tsx
  src/pages/Micar/MicarIndicator/styles.ts
Labels: dev-test

#3889 fix: zoom in
  src/pages/Micar/MicarIndicator/MapMicar/index.tsx
  src/pages/Micar/index.tsx
Labels: dev-test

#3890 fix: bug UI
  src/components/TransactionDetail/TransactionMetadata/Metadata/BolnisiWineDrawerConformity.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/index.tsx
Labels: dev-test

#3879 fix: bug ui anchor hash in dreps
  src/components/Dreps/DrepsList/index.tsx
Labels: 1.9.0

#3891 fix: fix bug micar
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
Labels: dev-test

#3892 fix: MET-1667 remove adahanle
  src/components/StakingLifeCycleSearch/index.tsx
Labels: dev-test

#3893 fix: MET-1667 remove adahanle
  src/components/StakingLifeCycleSearch/index.tsx
Labels: dev-test

#3895 fix: bug footer tablet
  src/components/commons/Layout/index.tsx
  src/components/commons/Layout/styles.ts
Labels: dev-test

#3897 fix: remaining vote in pool details
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3898 fix: MET-1667 remove adahanle
  src/components/StakingLifeCycleSearch/index.tsx
Labels: dev-test

#3899 fix: fomat date time
  src/components/TransactionDetail/TransactionMetadata/Metadata/BolnisiWineDrawerConformity.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/index.tsx
Labels: dev-test

#3900 fix: color text
  src/components/TransactionDetail/TransactionMetadata/Metadata/BolnisiWineDrawerConformity.tsx
Labels: dev-test

#3901 fix: fix bug micar
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
Labels: dev-test

#3903 fix: update UI
  src/components/TransactionDetail/TransactionMetadata/Metadata/BolnisiWineDrawerConformity.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/DefaultImageWine.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/index.tsx
Labels: dev-test

#3904 fix: bgr map
  src/pages/Micar/MicarIndicator/MapMicar/index.tsx
  src/pages/Micar/MicarIndicator/MapMicar/mockData.ts
Labels: dev-test

#3910 fix: fix bug Micar
  src/commons/utils/api.ts
  src/locales/en/translation.json
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarEmissions/index.tsx
Labels: dev-test

#3909 fix: backgr container map
  src/pages/Micar/MicarIndicator/MapMicar/styles.ts
Labels: dev-test

#3911 fix: fix bug micar chart history
  src/pages/Micar/MicarChart/index.tsx
Labels: dev-test

#3913 fix: fix bug micar
  src/pages/Micar/MicarEmissions/index.tsx
Labels: dev-test

#3908 Feat/met 1837 bolnisi display validate revocation certificate
  src/commons/resources/icons/revoked-icon.svg
  src/commons/resources/index.ts
  src/components/TransactionDetail/TransactionMetadata/Metadata/index.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/styles.ts
  src/types/transactions.d.ts
Labels: 1.9.0

#3906 fix: empty value in table createBy
  src/components/GovernanceActionDetails/CreatedBy/index.tsx
Labels: 1.9.0

#3856 feat: MET-1667 improve staking lifecycle search
  src/commons/hooks/useFetch.ts
  src/commons/utils/api.ts
  src/components/StakingLifeCycleSearch/index.tsx
  src/components/StakingLifeCycleSearch/styles.ts
Labels: 1.9.0

#3874 fix: replace domain ipfs
  src/components/GovernanceVotes/index.tsx
Labels: 1.9.0

#3894 fix: bug footer tablet
  src/components/commons/Layout/index.tsx
  src/components/commons/Layout/styles.ts
Labels: 1.9.0

#3896 fix: remaining vote in pool details
  src/components/GovernanceVotes/OverallVote.tsx
Labels: 1.9.0

#3915 Feat/met 2257 mandatory micar indicators
  package-lock.json
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/resources/icons/Earch.svg
  src/commons/resources/icons/Lighning.svg
  src/commons/resources/icons/clock-white.svg
  src/commons/resources/icons/clock.svg
  src/commons/resources/icons/earch-white.svg
  src/commons/resources/icons/lighning-white.svg
  src/commons/resources/icons/micar.svg
  src/commons/resources/icons/search-icon.svg
  src/commons/resources/icons/tree-white.svg
  src/commons/resources/icons/tree.svg
  src/commons/resources/icons/wash.svg
  src/commons/resources/icons/waste-white.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/components/commons/Layout/Header/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/components/commons/Layout/index.tsx
  src/locales/en/translation.json
  src/pages/Micar/MicarChart/index.tsx
  src/pages/Micar/MicarChart/styled.ts
  src/pages/Micar/MicarEmissions/index.tsx
  src/pages/Micar/MicarEmissions/styles.ts
  src/pages/Micar/MicarIndicator/index.tsx
  src/pages/Micar/MicarIndicator/styles.ts
  src/pages/Micar/index.tsx
  vite.config.ts
Labels: 1.9.0

#3912 feat/met 2258 create world map micar page
  src/commons/resources/icons/find-location-icon.svg
  src/commons/resources/icons/zoom-in-icon.svg
  src/commons/resources/icons/zoom-out-icon.svg
  src/commons/resources/index.ts
  src/locales/en/translation.json
  src/pages/Micar/MicarIndicator/MapMicar/Resource/topCities.ts
  src/pages/Micar/MicarIndicator/MapMicar/index.tsx
  src/pages/Micar/MicarIndicator/MapMicar/mockData.ts
  src/pages/Micar/MicarIndicator/MapMicar/styles.ts
  src/pages/Micar/MicarIndicator/MapMicar/type.ts
  src/pages/Micar/index.tsx
  src/pages/Micar/styles.ts
Labels: 1.9.0

#3854 Feat/met 2322 upgrade mui
  package-lock.json
  package.json
Labels: dev-test

#3916 fix: update code
  package-lock.json
  package.json
  src/pages/Micar/MicarIndicator/MapMicar/index.tsx
Labels: 1.9.0

#3917 fix: MET-2258 show icon move when move map
  src/pages/Micar/MicarIndicator/MapMicar/index.tsx
Labels: dev-test

#3921 Upgrade mui test
  .github/workflows/release.yaml
  package-lock.json
  package.json
  src/components/GovernanceActionDetails/OverviewHeader/VoteSubmitted/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/index.tsx
  src/locales/en/translation.json
  vite.config.ts
Labels: dev-test

#3853 feat: MET-2322 upgrade MUI 6.1.0
  package-lock.json
  package.json
Labels: 1.9.0

#3933 Test/sync test with main
  CHANGELOG.md
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/api/call-koios/koios.api.ts
  playwright/api/dtos/blockfrostNativeTokenInformation.dto.ts
  playwright/api/dtos/topADAHolders.dto.ts
  playwright/helpers/endpoints.ts
  playwright/pages/block-detail.page.ts
  playwright/pages/blocks-dashboard.page.ts
  playwright/pages/epoch-detail.page.ts
  playwright/pages/native-token.page.ts
  playwright/pages/pool.page.ts
  playwright/pages/script-detail.page.ts
  playwright/pages/token-detail.page.ts
  playwright/pages/top-ADA-holders.page.ts
  playwright/pages/transaction-detail.page.ts
  playwright/tests/e2e/features/native-token.feature
  playwright/tests/e2e/features/top-ADA-holders.feature
  playwright/tests/e2e/steps/native-token.steps.ts
  playwright/tests/e2e/steps/top-ADA-holders.step.ts
  src/commons/resources/icons/fetch-data-err-dark 2.svg
  src/commons/resources/icons/fetch-data-err-light 2.svg
  src/components/Contracts/Proposingviews/index 2.tsx
  src/components/Contracts/Votingviews/index 2.tsx
  src/components/Contracts/common/DataCardEllipsisText 2.tsx
  src/components/Contracts/common/ViewGorvernanceVotes 2.tsx
  src/components/Contracts/modals/ProposingOutputModal 2.tsx
  src/components/Contracts/modals/VotingOutputModal 2.tsx
  src/components/EpochDetail/EpochBlockList/index.tsx
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
  src/components/TopAddresses/ByADABalance/index.tsx
  src/components/TopAddresses/ByAmountStaked/index.tsx
  src/components/commons/DetailView/DetailViewToken.tsx
  src/components/commons/FetchDataErr/index 2.tsx
  src/components/commons/ViewBlocks/OutputVoting 2.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
  src/pages/Token/index.tsx
Labels: 1.9.0

#3923 fix: MET-2258 chang data world map
  src/pages/Micar/MicarIndicator/MapMicar/mockData.ts
  src/pages/Micar/MicarIndicator/MapMicar/styles.ts
Labels: 1.9.0

#3934 fix: MET-2258 chang data world map
  src/pages/Micar/MicarIndicator/MapMicar/mockData.ts
  src/pages/Micar/MicarIndicator/MapMicar/styles.ts
Labels: 1.10.0

#3926 feat: MET-2350 Remove column from block table
  src/pages/BlockList/index.tsx
Labels: dev-test

#3927 feat: Remove column from epoch table
  src/pages/Epoch/index.tsx
Labels: dev-test

#3928 feat: MET-2360 Remove column from transaction table view
  playwright/pages/blocks-dashboard.page.ts
  playwright/pages/epochs-dashboard.page.ts
  playwright/pages/transaction-overview.page.ts
  src/components/TransactionLists/index.tsx
Labels: dev-test

#3929 feat: MET-2361 Remove unneeded tiles from token detail page
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
  src/pages/TokenDetail/index.tsx
Labels: dev-test

#3932 fix: MET-2364 Get bolnisi numbers from API backend
  src/commons/utils/api.ts
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#3943 remove: automation test top ADA Page
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/api/dtos/topADAHolders.dto.ts
  playwright/helpers/endpoints.ts
  playwright/pages/top-ADA-holders.page.ts
  playwright/tests/e2e/features/top-ADA-holders.feature
  playwright/tests/e2e/steps/top-ADA-holders.step.ts
Labels: dev-test

#3925 feat: MET-2356 Remove colum from token table
  src/pages/Token/index.tsx
Labels: dev-test

#3931 Feat/met 2366 remove top token holder test
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
  src/pages/TokenDetail/index.tsx
Labels: dev-test

#3834 Fix/input zero stake test
  src/components/Dreps/DrepFilter/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
Labels: dev-test

#3947 Fix/input filter test
  src/components/Dreps/DrepFilter/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3948 fix: bug filter
  src/components/Dreps/DrepFilter/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3949 feat: MET-2361 Remove unneeded tiles from token details
  src/components/TokenDetail/TokenOverview/index.tsx
Labels: dev-test

#3952 Fix/token bug UI test
  src/pages/Token/index.tsx
Labels: dev-test

#3954 Fix/token bug UI test
  src/components/commons/DetailView/DetailViewToken.tsx
Labels: dev-test

#3953 fix: bug filter
  src/components/Dreps/DrepFilter/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3957 fix/lowest balance chart
  src/components/DelegationDetail/DelegationDetailChart/index.tsx
Labels: dev-test

#3955 fix: token bug ui
  src/components/commons/DetailView/DetailViewToken.tsx
Labels: dev-test
