Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-05, with the labels that each got.

#3380 chore: update version release
  .github/workflows/release.yaml
  package.json
Labels: 1.3.0

#3382 Fix/disable filter pool
  .github/workflows/release.yaml
  package.json
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3384 Fix/met 1965 remove barchart
  src/components/Dreps/DrepsOverview/index.tsx
Labels: 1.3.0

#3381 fix: MET-2111 disbale filter when not avaiable
  src/components/DelegationPool/DelegationList/styles.ts
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/locales/en/translation.json
Labels: 1.3.0

#3389 fix: MET-2057 fix slot number right menu in blocks page
  src/components/commons/DetailView/DetailViewBlock.tsx
  src/types/block.d.ts
Labels: dev-test

#3391 fix: MET 2035 search suggestion list is not working
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: dev-test

#3394 fix: MET-2039 update filter
  src/components/Dreps/DrepsList/index.tsx
Labels: dev-test

#3395 feat: MET-2039 add new option
  src/components/Dreps/DrepFilter/index.tsx
  src/components/Dreps/DrepsList/index.tsx
Labels: dev-test

#3396 fix: MET-2103 disable stake key not found
  src/components/AddressDetail/AddressHeader/index.tsx
  src/components/share/CardAddress/index.tsx
Labels: dev-test

#3399 fix: MET-2039 add icon select filter
  src/components/Dreps/DrepFilter/index.tsx
Labels: dev-test

#3401 Fix/add block producer
  src/commons/resources/icons/king-icon.svg
  src/commons/resources/icons/tooltip-icon.svg
  src/commons/resources/index.ts
  src/components/BlockDetail/BlockOverview/index.tsx
  src/locales/en/translation.json
  src/pages/BlockDetail/index.tsx
  src/types/block.d.ts
Labels: dev-test

#3386 fix: MET-2057 fix link to cardano docs
  src/commons/menus.ts
Labels: 1.3.0

#3388 fix: MET-2057 fix slot number right menu in blocks page
  src/components/commons/DetailView/DetailViewBlock.tsx
  src/types/block.d.ts
Labels: 1.3.0

#3402 fix: MET-2039 add clear value daterange
  src/components/Dreps/DrepFilter/index.tsx
Labels: dev-test

#3403 fix: MET 2035 search suggestion list is not working
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: dev-test

#3407 Fix/tz not reload
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
Labels: dev-test

#3393 Feat/met 2039 add drep filter
  src/commons/resources/icons/DrepId.svg
  src/commons/resources/icons/activeStakeDrep.svg
  src/commons/resources/index.ts
  src/commons/utils/api.ts
  src/components/Dreps/DrepFilter/index.tsx
  src/components/Dreps/DrepFilter/styles.ts
  src/components/Dreps/DrepsList/index.tsx
  src/components/commons/CustomFilter/DateRangeModal.tsx
  src/locales/en/translation.json
Labels: 1.3.0

#3408 fix: MET-2035 fix search suggestion
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
  src/locales/en/translation.json
  src/types/index.d.ts
Labels: dev-test

#3409 fix: MET-2035 update title
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
Labels: dev-test

#3404 fix: MET-2146 remove disclaimer in token details page
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/locales/en/translation.json
Labels: 1.3.0

#3410 fix: fix pool bookmark
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
Labels: dev-test

#3411 fix: MET-2035 update search pool
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: dev-test

#3406 fix: MET-2112 change tz not reload when user login
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
Labels: 1.3.0

#3398 feat: MET 2019 add block producer
  src/commons/resources/icons/king-icon.svg
  src/commons/resources/icons/tooltip-icon.svg
  src/commons/resources/index.ts
  src/components/BlockDetail/BlockOverview/index.tsx
  src/locales/en/translation.json
  src/pages/BlockDetail/index.tsx
  src/types/block.d.ts
Labels: 1.3.0

#3390 fix: MET 2035 search suggestion list is not working
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
  src/locales/en/translation.json
  src/types/index.d.ts
Labels: 1.3.0

#3412 Fix/met 2103 disable stake key not found
  src/components/StakingLifeCycle/DelegatorLifecycle/ReportComposerModal/StepReviewModal.tsx
  src/pages/ContractDetail/ContractDetail.test.tsx
Labels: dev-test

#3397 fix: MET-2103 disable stake key not found
  src/components/AddressDetail/AddressHeader/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/ReportComposerModal/StepReviewModal.tsx
  src/components/share/CardAddress/index.tsx
  src/pages/ContractDetail/ContractDetail.test.tsx
Labels: 1.3.0

#3415 fix: fix typo
  src/locales/en/translation.json
Labels: 1.3.0

#3422 Feat/update gov
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/GovernanceVotes/OverviewVote.tsx
  src/components/GovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/pages/NativeScriptsAndSC/Card.tsx
  src/types/drep.d.ts
Labels: dev-test

#3424 fix: hide icon tick when clear date
  src/pages/ProtocolParameter/index.tsx
Labels: dev-test

#3428 fix: MET-2055 update UI
  src/components/GovernanceVotes/OverallVote.tsx
  src/locales/en/translation.json
Labels: dev-test

#3429 fix: MET-2055 add tooltip
  src/components/GovernanceVotes/OverallVote.tsx
  src/locales/en/translation.json
Labels: dev-test

#3413 fix: change color vote mapping design
  src/components/GovernanceVotes/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.3.0

#3419 fix: fix search transaction in tab delegation
  src/components/TabularView/StakeTab/Tabs/DelegationTab.tsx
Labels: 1.3.0

#3431 fix: fix icon tick when clear change date
  src/components/commons/CustomFilter/index.tsx
Labels: dev-test

#3425 fix: fix search withdrawall history
  src/components/TabularView/StakeTab/Tabs/WithdrawalHistoryTab.tsx
Labels: 1.3.0

#3423 fix: hide icon tick when clear date
  src/pages/ProtocolParameter/index.tsx
Labels: 1.3.0

#3433 fix: MET-2055 update UI
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3434 fix: MET-2055 update show ada format
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3435 fix: MET-2055 update tooltip
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3436 fix: MET-2055 update tooltip
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3437 fix: MET-2055 disable gov cannot vote
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/GovernanceVotes/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3438 fix: MET-2055 update tooltip
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3439 fix: update logic filter
  src/components/TabularView/StakeTab/Tabs/RewardsDistributionTab.tsx
  src/components/commons/CustomFilter/index.tsx
Labels: dev-test

#3440 fix: MET-2055 update UI
  src/components/Dreps/DrepFilter/index.tsx
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3441 fix: MET-2055 add flag hide mock đata
  docker-compose.yml
  env.global.tmp.js
  src/commons/utils/constants.ts
  src/components/GovernanceVotes/OverallVote.tsx
  vite.config.ts
Labels: dev-test

#3442 fix: MET-2055 update condition show ada
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3444 fix: MET-2055 update flag
  src/commons/utils/constants.ts
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3445 fix: MET-2055 update flag
  src/commons/utils/constants.ts
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3446 fix: MET-2055 update tooltip
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3447 fix: MET-2055 update show data
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3452 Fix/drep filter test
  .github/workflows/deploy.yaml
  .github/workflows/e2e_tests_dev.yaml
  .github/workflows/e2e_tests_staging.yaml
  .github/workflows/e2e_tests_uat.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/smoke_tests.yaml
  .github/workflows/unit_tests.yaml
  src/components/Dreps/DrepFilter/index.tsx
  src/components/Dreps/DrepsList/index.tsx
Labels: dev-test

#3450 fix: drep filter
  src/components/Dreps/DrepFilter/index.tsx
  src/components/Dreps/DrepsList/index.tsx
Labels: 1.0.0

#3453 fix: cannot remove number in input
  src/components/Dreps/DrepFilter/index.tsx
Labels: dev-test

#3454 fix: cannot remove number in input
  src/components/Dreps/DrepFilter/index.tsx
Labels: 1.3.0

#3455 fix: update filter
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3456 fix: update filter
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: 1.3.0

#3457 fix: MET_2019 update tooltip
  src/components/BlockDetail/BlockOverview/index.tsx
Labels: dev-test

#3459 fix: search all filter
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: dev-test

#3421 Feat/met 2055 update governance votes
  docker-compose.yml
  env.global.tmp.js
  src/commons/utils/constants.ts
  src/components/Dreps/DrepFilter/index.tsx
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/GovernanceVotes/OverviewVote.tsx
  src/components/GovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/pages/NativeScriptsAndSC/Card.tsx
  src/types/drep.d.ts
  vite.config.ts
Labels: 1.3.0

#3458 fix: fix search all filter
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: 1.3.0

#3460 fix: update requirment
  src/components/BlockDetail/BlockOverview/index.tsx
Labels: dev-test

#3448 feat: MET-2019 update case
  src/components/BlockDetail/BlockOverview/index.tsx
  src/types/block.d.ts
Labels: 1.3.0

#3430 fix: fix icon tick when clear change date
  src/components/TabularView/StakeTab/Tabs/RewardsDistributionTab.tsx
  src/components/commons/CustomFilter/index.tsx
Labels: 1.3.0

#3462 Fix/header table pool page site test
  src/components/DelegationPool/DelegationList/styles.ts
Labels: dev-test

#3464 fix: show threshold in tooltip
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3468 fix: MET-2063 fix token name not display
  src/components/NativeScriptsDetail/Tabs/Token.tsx
Labels: dev-test

#3469 fix: MET-2055 update tooltip CC disable
  src/locales/en/translation.json
Labels: dev-test

#3472 fix: MET-2055 update tooltip
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3470 fix: call multi api when click tab in pool detail page
  src/pages/DelegationDetail/index.tsx
Labels: hold, 1.3.0

#3471 fix: call multi api when click tab in pool detail page
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3473 fix: MET-2055 update tooltip CC disable
  src/components/GovernanceVotes/OverallVote.tsx
  src/locales/en/translation.json
Labels: 1.3.0

#3474 Fix/update sign in payload
  src/components/commons/Layout/Header/ConnectWallet/index.tsx
Labels: dev-test

#3475 fix: update signin payload
  src/components/commons/Layout/Header/ConnectWallet/index.tsx
Labels: 1.3.0

#3479 fix: common call multi api when click only tab
  src/components/StakeDetail/StakeTab/Tabs/DelegationHistoryTab.tsx
  src/components/StakeDetail/StakeTab/Tabs/InstantaneousTab.tsx
  src/components/StakeDetail/StakeTab/Tabs/StakeHistoryTab.tsx
  src/components/StakeDetail/StakeTab/Tabs/TransactionTab.tsx
  src/components/StakeDetail/StakeTab/Tabs/WithdrawalHistoryTab.tsx
  src/components/StakeDetail/StakeTab/index.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/Tabs/DeregsitrationTab.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/Tabs/OperatorReward.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/Tabs/PoolRegistrationTab.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/Tabs/PoolUpdateTab.tsx
  src/components/TabularView/StakeTab/Tabs/DelegationTab.tsx
  src/components/TabularView/StakeTab/Tabs/DeregistrationTab.tsx
  src/components/TabularView/StakeTab/Tabs/RewardsDistributionTab.tsx
  src/components/TabularView/StakeTab/Tabs/StakeRegistrationTab.tsx
  src/components/TabularView/StakeTab/Tabs/WithdrawalHistoryTab.tsx
  src/components/TokenDetail/TokenTableData/TokenMinting.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
Labels: dev-test

#3480 fix: Stake Address Deregistration
  src/pages/Stake/index.tsx
  src/types/stakeKey.d.ts
Labels: dev-test

#3482 Fix/met 2055 not straight line
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3485 feat: MET-2062 add button in footer
  src/components/commons/Layout/Footer/index.tsx
Labels: dev-test

#3486 feat: update coding
  src/commons/utils/constants.ts
  src/components/commons/Layout/Footer/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3481 fix: Stake Address Deregistration
  src/pages/Stake/index.tsx
  src/types/stakeKey.d.ts
Labels: 1.3.0

#3484 feat: MET-2062 add button in footer
  src/commons/utils/constants.ts
  src/components/commons/Layout/Footer/index.tsx
  src/locales/en/translation.json
Labels: 1.4.0

#3488 Fix/met 2150 show type index governance
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
Labels: dev-test

#3467 Fix: met 2063 token name not display
  src/components/NativeScriptsDetail/Tabs/Token.tsx
Labels: 1.3.0

#3478 fix: common call multi api when click only tab
  src/components/StakeDetail/StakeTab/Tabs/DelegationHistoryTab.tsx
  src/components/StakeDetail/StakeTab/Tabs/InstantaneousTab.tsx
  src/components/StakeDetail/StakeTab/Tabs/StakeHistoryTab.tsx
  src/components/StakeDetail/StakeTab/Tabs/TransactionTab.tsx
  src/components/StakeDetail/StakeTab/Tabs/WithdrawalHistoryTab.tsx
  src/components/StakeDetail/StakeTab/index.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/Tabs/DeregsitrationTab.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/Tabs/OperatorReward.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/Tabs/PoolRegistrationTab.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/Tabs/PoolUpdateTab.tsx
  src/components/TabularView/StakeTab/Tabs/DelegationTab.tsx
  src/components/TabularView/StakeTab/Tabs/DeregistrationTab.tsx
  src/components/TabularView/StakeTab/Tabs/RewardsDistributionTab.tsx
  src/components/TabularView/StakeTab/Tabs/StakeRegistrationTab.tsx
  src/components/TabularView/StakeTab/Tabs/WithdrawalHistoryTab.tsx
  src/components/TokenDetail/TokenTableData/TokenMinting.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
Labels: 1.3.0

#3483 fix/met 2055 not straight line
  src/components/GovernanceVotes/OverallVote.tsx
Labels: 1.3.0

#3490 fix: MET-2152 fix pool filter
  src/components/DelegationPool/DelegationList/index.tsx
Labels: dev-test

#3493 fix: MET-2062 hover tooltip
  src/components/commons/Layout/Footer/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3495 fix: MET-2195 update show epoch progress
  src/components/SystemLoader/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailView/DetailViewEpoch.tsx
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/types/epoch.d.ts
Labels: 1.3.0

#3496 fix: MET-2195 update show epoch progress
  src/components/SystemLoader/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailView/DetailViewEpoch.tsx
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/types/epoch.d.ts
Labels: dev-test

#3500 fix: update coding dreps detail
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3504 fix: MET-2052 pools filters
  src/components/DelegationPool/DelegationList/index.tsx
Labels: 1.3.0

#3511 Fix/met 2150 bug UI test
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3418 test: Add dashboard content check and search epochs and blocks tests
  playwright.config.ts
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/api/call-blockfrost/blockfrost.service.ts
  playwright/helpers/SearchFilters.ts
  playwright/helpers/endpoints.ts
  playwright/pages/block-detail.page.ts
  playwright/pages/dashboard.page.ts
  playwright/pages/epoch-detail.page.ts
  playwright/tests/e2e/features/dashboard.feature
  playwright/tests/e2e/steps/dashboard.steps.ts
  playwright/tests/e2e/steps/data-consistency.steps.ts
  playwright/tests/e2e/steps/sign-in.steps.ts
Labels: Automation Test

#3514 fix: MET-2023 Identify new SC
  src/components/Contracts/Proposingviews/index.tsx
  src/components/Contracts/Votingviews/index.tsx
  src/components/Contracts/common/DataCardEllipsisText.tsx
  src/components/Contracts/index.tsx
  src/components/Contracts/modals/ProposingOutputModal.tsx
  src/components/Contracts/modals/VotingOutputModal.tsx
  src/components/GovernanceVotes/OverviewVote.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/commons/ViewBlocks/styles.ts
  src/locales/en/translation.json
Labels: dev-test

#3509 fix: MET-2150 Bug UI
  src/components/GovernanceVotes/index.tsx
Labels: 1.3.0

#3505 fix: MET-2200 UAT Preprod Pool Details Cards are not loading
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
  src/pages/DelegationDetail/index.tsx
Labels: 1.3.0

#3489 fix/MET-2152 pool filter
  src/components/DelegationPool/DelegationList/index.tsx
Labels: 1.4.0

#3492 fix/met 2062 hover tooltip
  src/components/commons/Layout/Footer/index.tsx
  src/locales/en/translation.json
Labels: 1.4.0

#3498 fix/met 2187 clear data zero and NA
  src/components/Home/Statistic/index.tsx
  src/components/Home/Trending/TransactionChart/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.4.0

#3519 fix: MET-2023 Identiy new SC
  src/components/Contracts/Proposingviews/index.tsx
  src/components/Contracts/common/ContractItem.tsx
  src/components/Contracts/common/DataCardEllipsisText.tsx
  src/components/Contracts/common/GovernanceActionCard.tsx
  src/components/Contracts/common/styles.ts
  src/components/Contracts/index.tsx
  src/components/Contracts/modals/ProposingOutputModal.tsx
  src/components/commons/InfoSolidIcon/index.tsx
  src/components/commons/ViewBlocks/styles.ts
  src/types/transactions.d.ts
Labels: dev-test

#3523 feat: MET-2049 hide filter and time when fetch api fail
  src/commons/hooks/useFetch.ts
  src/commons/hooks/useFetchList.ts
  src/commons/resources/icons/fetch-data-err-dark.svg
  src/commons/resources/icons/fetch-data-err-light.svg
  src/commons/resources/index.ts
  src/components/ContractDetail/ContractDetailContent/TokenTransaction/index.tsx
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/Dreps/DrepsList/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/PolicyDetail/PolicyTable/index.tsx
  src/components/ReportGeneratedStakingDetail/StakeyTabs/DelegationTab.tsx
  src/components/ReportGeneratedStakingDetail/StakeyTabs/RewardsDistributionTab.tsx
  src/components/ReportGeneratedStakingDetail/StakeyTabs/WithdrawalHistoryTab.tsx
  src/components/TabularView/StakeTab/Tabs/DelegationTab.tsx
  src/components/TabularView/StakeTab/Tabs/RewardsDistributionTab.tsx
  src/components/TabularView/StakeTab/Tabs/WithdrawalHistoryTab.tsx
  src/components/TokenDetail/TokenTableData/TokenMinting.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TopAddresses/ByADABalance/index.tsx
  src/components/TopAddresses/ByAmountStaked/index.tsx
  src/components/TransactionLists/index.tsx
  src/components/commons/FetchDataErr/index.tsx
  src/components/commons/Table/index.tsx
  src/pages/BlockList/index.tsx
  src/pages/ContractList/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/Epoch/index.tsx
  src/pages/InstantRewards/index.tsx
  src/pages/ProtocolParameter/index.tsx
  src/pages/RegistrationPools/index.tsx
  src/pages/Stake/index.tsx
  src/pages/StakeDelegations/index.tsx
  src/pages/Token/index.tsx
  src/types/table.d.ts
Labels: dev-test

#3525 fix: MET-2205 update link in table holder token detail
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
Labels: 1.4.0

#3530 fix: MET-2049 update logic
  src/components/commons/Table/index.tsx
Labels: dev-test

#3531 fix: MET-2023 Identity new SC
  src/components/Contracts/Proposingviews/index.tsx
  src/components/Contracts/index.tsx
  src/components/TransactionDetail/TransactionMetadata/index.tsx
Labels: dev-test

#3534 fix: calc net amount in withdrawal stake report
  src/components/ReportGeneratedStakingDetail/StakeyTabs/WithdrawalHistoryTab.tsx
Labels: dev-test

#3535 fix: calc timeline net amount
  src/components/StakingLifeCycle/DelegatorLifecycle/Withdraw/WithdrawDraw/index.tsx
Labels: dev-test

#3536 Feat/met 2023 identify new sc purposes and visualization patterns
  src/components/Contracts/common/styles.ts
  src/components/TransactionDetail/TransactionMetadata/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3537 fix: MET-2023 Identify new SC
  src/components/Contracts/common/DataCardEllipsisText.tsx
Labels: dev-test

#3533 fix: calc net amount in withdrawal stake report
  src/components/ReportGeneratedStakingDetail/StakeyTabs/WithdrawalHistoryTab.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Withdraw/WithdrawDraw/index.tsx
Labels: 1.4.0

#3540 Feat/met 2062 add button in footer
  src/commons/utils/constants.ts
  src/components/commons/Layout/Footer/index.tsx
  src/locales/en/translation.json
Labels: 1.3.0

#3487 fix: MET-2150 update type index governance
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
Labels: 1.4.0

#3532 Fix/met 2170 add missing data testid for dashboard elements test
  src/components/Home/LatestStories/index.tsx
  src/components/Home/LatestTransactions/index.tsx
Labels: dev-test

#3543 fix: MET-2049 update logic table when call api error
  src/commons/hooks/useFetch.ts
  src/commons/hooks/useFetchList.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/EpochDetail/EpochBlockList/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/TopAddresses/ByADABalance/index.tsx
  src/components/TopAddresses/ByAmountStaked/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/NativeScriptsAndSC/TabNativeScripts.tsx
  src/pages/NativeScriptsAndSC/TabSmartContracts.tsx
  src/pages/ProtocolParameter/index.tsx
  src/pages/StakingLifecycle/index.tsx
  src/pages/Token/index.tsx
Labels: dev-test

#3545 fix: MET-2170 Add missing data testid for dashboard
  src/components/Home/LatestStories/index.tsx
  src/components/Home/LatestTransactions/index.tsx
Labels: 1.4.0

#3546 fix/incorrect last update drep detail
  src/pages/DrepDetail/index.tsx
Labels: dev-test
