Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-03, with the labels that each got.

#3117 fix: MET-1991 save ADA price to local
  src/components/AddressDetail/AddressHeader/index.tsx
  src/components/Home/Statistic/index.tsx
  src/components/SystemLoader/index.tsx
  src/stores/system.ts
  src/types/system.d.ts
Labels: 1.0.0

#3119 Fix : error when filter protocol parameter
  src/pages/ProtocolParameter/index.tsx
Labels: sota_testing

#3121 fix: dont pass newCostModel without costModel
  src/pages/ProtocolParameter/index.tsx
Labels: sota_testing

#3122 chore: update version package json
  .github/workflows/release.yaml
  package.json
Labels: 1.0.0

#3124 Fix : update data modal protocol
  .github/workflows/release.yaml
  package.json
  src/pages/ProtocolParameter/index.tsx
Labels: sota_testing

#3123 Fix : update data modal protocol
  src/pages/ProtocolParameter/index.tsx
Labels: 1.0.0

#3128 fix: MET-1896 update UPLC
  index.html
  src/commons/utils/helper.ts
  src/components/Contracts/UPLCTree/index.tsx
  src/components/Contracts/common/CompiledCodeDataCard.tsx
Labels: sota_testing

#3125 Fix: block click on textarea
  src/components/ParseScriptModal/index.tsx
Labels: 1.0.0

#3129 fix: MET-1896 move lib folder
  index.html
  lib/pkg/README.md
  lib/pkg/package.json
  lib/pkg/uplc_js.d.ts
  lib/pkg/uplc_js.js
  lib/pkg/uplc_js_bg.wasm
  lib/pkg/uplc_js_bg.wasm.d.ts
Labels: sota_testing

#3127 fix: MET-1896 update UPLC
  index.html
  lib/pkg/README.md
  lib/pkg/package.json
  lib/pkg/uplc_js.d.ts
  lib/pkg/uplc_js.js
  lib/pkg/uplc_js_bg.wasm
  lib/pkg/uplc_js_bg.wasm.d.ts
  src/commons/utils/helper.ts
  src/components/Contracts/UPLCTree/index.tsx
  src/components/Contracts/common/CompiledCodeDataCard.tsx
Labels: 1.0.0

#3131 fix: update min height custom modal
  src/components/commons/CustomModal/styles.ts
Labels: sota_testing

#3136 Fix: sync sort table staking lifecycle
  src/components/commons/CustomFilter/index.tsx
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/pages/StakingLifecycle/index.tsx
Labels: sota_testing

#3135 Fix: remove tooltip on native scripts
  src/components/NativeScriptsDetail/Tabs/MinttingBurningPolicy.tsx
Labels: 1.0.0

#3139 fix: remove params when reset data
  src/components/commons/CustomFilter/index.tsx
Labels: sota_testing

#3138 fix: remove scroll on ModalContent
  src/components/Contracts/modals/styles.ts
Labels: sota_testing

#3140 fix: update logic display circle on epoch
  src/components/commons/Epoch/FirstEpoch/index.tsx
Labels: sota_testing

#3141 fix: update max height of modal
  src/components/commons/CustomModal/styles.ts
Labels: sota_testing

#3132 Fix : update bookmark logic
  src/components/commons/BookmarkIcon/index.tsx
Labels: 1.0.0

#3143 chore: change key translate and condition
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/pages/StakingLifecycle/index.tsx
Labels: sota_testing

#3130 Fix: update min height custom modal
  src/components/Contracts/modals/styles.ts
  src/components/commons/CustomModal/styles.ts
Labels: 1.0.0

#3137 fix: sync sort table on staking lifecycle
  src/components/commons/CustomFilter/index.tsx
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/pages/StakingLifecycle/index.tsx
Labels: question, 1.0.0

#3144 Fix : met 1972 epoch status display is incorrect while syncing
  src/components/commons/Epoch/FirstEpoch/index.tsx
Labels: 1.0.0

#3146 Fix/met 2030 fix warn console
  lib/pkg/uplc_js.js
Labels: sota_testing

#3148 Fix/met 2015 fix smoke test failure
  src/components/Home/Statistic/Statistic.test.tsx
  src/components/NativeScriptsDetail/Tabs/NativeScriptDetailTabs.test.tsx
  src/components/StakeDetail/StakeAnalytics/StakeAnalytics.test.tsx
  src/components/StakeDetail/StakeOverview/index.tsx
  src/components/StakeDetail/StakeOverview/styles.ts
  src/components/StakingLifeCycle/SPOLifecycle/OperatorRewards/SPOOperatorRewards.test.tsx
  src/components/commons/CIP25Badge/CIP25Badge.test.tsx
  src/components/commons/ConnectWalletModal/ConnectWalletModal.test.tsx
  src/components/commons/DropdownTokens/DropdownTokens.test.tsx
  src/components/commons/Layout/Header/Header.test.tsx
  src/components/commons/Layout/Sidebar/Sidebar.test.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/SidebarMenu.test.tsx
  src/pages/AddressWalletDetail/AddressWalletDetail.test.tsx
  src/pages/ProtocolParameter/ProtocolParameter.test.tsx
  src/pages/StakeDetail/StakeDetail.test.tsx
  src/types/coingecko.d.ts
Labels: 1.1.0

#3155 Feat : MET 1957 pool detail view
  src/commons/resources/icons/arrow-left-white.svg
  src/commons/resources/icons/voteAbstain.svg
  src/commons/resources/icons/voteNo.svg
  src/commons/resources/icons/voteNone.svg
  src/commons/resources/icons/voteYes.svg
  src/commons/resources/icons/votes.svg
  src/commons/resources/index.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/DelegationDetail/DelegationDetailList/styles.ts
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
  src/types/delegationPools.d.ts
Labels: dev-test

#3158 Feat/met 1976 support plutus v3 test
  src/commons/utils/constants.ts
  src/components/Contracts/common/ContractItem.tsx
  src/components/Home/Statistic/Statistic.test.tsx
  src/components/NativeScriptsDetail/Tabs/NativeScriptDetailTabs.test.tsx
  src/components/StakeDetail/StakeAnalytics/StakeAnalytics.test.tsx
  src/components/StakeDetail/StakeOverview/index.tsx
  src/components/StakeDetail/StakeOverview/styles.ts
  src/components/StakingLifeCycle/SPOLifecycle/OperatorRewards/SPOOperatorRewards.test.tsx
  src/components/commons/CIP25Badge/CIP25Badge.test.tsx
  src/components/commons/ConnectWalletModal/ConnectWalletModal.test.tsx
  src/components/commons/DropdownTokens/DropdownTokens.test.tsx
  src/components/commons/Layout/Header/Header.test.tsx
  src/components/commons/Layout/Sidebar/Sidebar.test.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/SidebarMenu.test.tsx
  src/locales/en/translation.json
  src/pages/AddressWalletDetail/AddressWalletDetail.test.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
  src/pages/NativeScriptsAndSC/TabSmartContracts.tsx
  src/pages/ProtocolParameter/ProtocolParameter.test.tsx
  src/pages/StakeDetail/StakeDetail.test.tsx
  src/types/coingecko.d.ts
Labels: dev-test

#3160 feat: MEAT 1957 pool details view
  src/commons/resources/icons/action-type.svg
  src/commons/resources/icons/anchor-text.svg
  src/commons/resources/icons/black-cirle-copy.svg
  src/commons/resources/icons/current-status.svg
  src/commons/resources/icons/expiry-date.svg
  src/commons/resources/icons/governanceId.svg
  src/commons/resources/icons/submission-date.svg
  src/commons/resources/icons/vote.svg
  src/commons/resources/icons/voting-power.svg
  src/commons/resources/icons/warning-black.svg
  src/commons/resources/index.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/DelegationDetail/DelegationDetailList/styles.ts
  src/components/commons/CardGovernanceVotes/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3161 Fix : fix conflict translation
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3165 feat: MET-1963 update update time
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3166 fix: MET-2030 update code
  lib/pkg/uplc_js.js
Labels: dev-test

#3167 fix: MET-2030 update code
  lib/pkg/uplc_js.js
Labels: dev-test

#3147 fix: MET-2030 fix warn console
  lib/pkg/uplc_js.js
Labels: 1.1.0

#3105 Merge 1.0.0 into main
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  index.html
  lib/pkg/README.md
  lib/pkg/package.json
  lib/pkg/uplc_js.d.ts
  lib/pkg/uplc_js.js
  lib/pkg/uplc_js_bg.wasm
  lib/pkg/uplc_js_bg.wasm.d.ts
  package-lock.json
  package.json
  src/commons/hooks/useDisableJsonKey.tsx
  src/commons/hooks/useFetchIntervalFromCoinGecko.ts
  src/commons/utils/helper.ts
  src/components/AddressDetail/AddressHeader/index.tsx
  src/components/AddressTransactionList/index.tsx
  src/components/ContractDetail/AddressOverview/index.tsx
  src/components/Contracts/UPLCTree/index.tsx
  src/components/Contracts/common/CompiledCodeDataCard.tsx
  src/components/Contracts/modals/styles.ts
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/Home/Statistic/index.tsx
  src/components/NativeScriptsDetail/Tabs/MinttingBurningPolicy.tsx
  src/components/ParseScriptModal/index.tsx
  src/components/StakeDetail/StakeTab/Tabs/TransactionTab.tsx
  src/components/StakingLifeCycle/SPOLifecycle/OperatorRewards/index.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/TabularOverview/index.tsx
  src/components/SystemLoader/index.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/BolnisiWineDrawer.tsx
  src/components/TransactionDetail/TransactionMetadata/Metadata/index.tsx
  src/components/TransactionDetail/TransactionMetadata/ProtocolUpdate/index.tsx
  src/components/TransactionDetail/TransactionMetadata/ProtocolUpdate/styles.ts
  src/components/TransactionDetail/TransactionMetadata/TransactionSignatories/styles.ts
  src/components/commons/BookmarkIcon/index.tsx
  src/components/commons/CustomFilter/index.tsx
  src/components/commons/CustomModal/styles.ts
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/components/commons/Layout/styles.ts
  src/locales/en/translation.json
  src/pages/ForgotPassword/index.tsx
  src/pages/ProtocolParameter/index.tsx
  src/pages/RegistrationPools/index.tsx
  src/pages/Stake/index.tsx
  src/pages/StakingLifecycle/index.tsx
  src/stores/system.ts
  src/types/system.d.ts
  tsconfig.json
Labels: 1.0.0

#3169 Feat : met 1957 update filter
  src/commons/resources/icons/repeat-votes.svg
  src/commons/resources/index.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
  src/pages/DelegationDetail/styles.ts
Labels: dev-test

#3170 Fix/met 1960 pool overview test
  src/components/DelegationPool/DelegationList/index.tsx
  src/locales/en/translation.json
  src/types/delegationPools.d.ts
Labels: dev-test

#3173 Feat/met 1963 drep details view test
  src/commons/resources/icons/dropdown.svg
  src/commons/resources/index.ts
  src/commons/utils/api.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
  src/pages/DrepDetail/styles.ts
  src/types/drep.d.ts
  src/types/stakeKey.d.ts
Labels: dev-test

#3174 Fix: MET 1957 fix bug ui governance votes
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CopyButton/index.tsx
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3177 Feat/met 1963 drep details view test
  src/commons/utils/api.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/pages/DrepDetail/index.tsx
  src/types/delegationPools.d.ts
Labels: dev-test

#3178 fix: MET-1960 update show feild format
  src/components/DelegationPool/DelegationList/index.tsx
Labels: dev-test

#3179 chore: update verion release
  .github/workflows/release.yaml
  package.json
Labels: 1.1.0

#3182 Met 2034 change notice text sanchonet test
  .github/workflows/release.yaml
  package.json
  src/components/commons/Layout/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3185 fix: MET-1963 show drep id
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3189 fix: MET-1960 update show N/a
  src/components/DelegationPool/DelegationList/index.tsx
Labels: dev-test

#3181 fix: MET-2034 change notice text sanchonet
  src/components/commons/Layout/index.tsx
  src/locales/en/translation.json
Labels: 1.1.0

#3157 feat: MET-1976 update contract page
  src/commons/utils/constants.ts
  src/components/Contracts/common/ContractItem.tsx
  src/locales/en/translation.json
  src/pages/NativeScriptsAndSC/Card.tsx
  src/pages/NativeScriptsAndSC/TabSmartContracts.tsx
Labels: 1.1.0

#3190 fix: MET-1960 show pool retired
  src/components/DelegationPool/DelegationList/index.tsx
Labels: dev-test

#3192 Feat/met 1957 pools details view
  src/commons/utils/api.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/components/commons/CustomFilter/styles.ts
  src/components/commons/Table/index.tsx
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3193 Feat/met 1957 pools details view
  src/commons/utils/constants.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3195 Feat/met 1963 drep details view dev test
  src/commons/resources/icons/DisclaimerIcon.svg
  src/commons/resources/index.ts
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
  src/types/drep.d.ts
Labels: dev-test

#3194 Feat/MET1957 pools detail view
  src/commons/resources/icons/action-type.svg
  src/commons/resources/icons/activeVote.svg
  src/commons/resources/icons/anchor-text.svg
  src/commons/resources/icons/arrow-left-white.svg
  src/commons/resources/icons/black-cirle-copy.svg
  src/commons/resources/icons/createdrep.svg
  src/commons/resources/icons/current-status.svg
  src/commons/resources/icons/delegatorsDrep.svg
  src/commons/resources/icons/descriptonDrep.svg
  src/commons/resources/icons/expiry-date.svg
  src/commons/resources/icons/governanceId.svg
  src/commons/resources/icons/governanceVotes.svg
  src/commons/resources/icons/liifetimeVoteDrep.svg
  src/commons/resources/icons/liveStake.svg
  src/commons/resources/icons/repeat-votes.svg
  src/commons/resources/icons/stakingLifecycle.svg
  src/commons/resources/icons/submission-date.svg
  src/commons/resources/icons/vote.svg
  src/commons/resources/icons/voteAbstain.svg
  src/commons/resources/icons/voteNo.svg
  src/commons/resources/icons/voteNone.svg
  src/commons/resources/icons/voteYes.svg
  src/commons/resources/icons/votes.svg
  src/commons/resources/icons/voting-power.svg
  src/commons/resources/icons/warning-black.svg
  src/commons/resources/index.ts
  src/commons/utils/api.ts
  src/commons/utils/constants.ts
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/DelegationDetail/DelegationDetailList/styles.ts
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
  src/pages/DelegationDetail/styles.ts
  src/pages/NativeScriptsAndSC/Card.tsx
  src/types/delegationPools.d.ts
Labels: 1.1.0

#3196 Feat/met 1963 drep details view dev test
  CHANGELOG.md
  package-lock.json
  package.json
  src/commons/resources/icons/stakingLifecycle.svg
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
  src/types/delegationPools.d.ts
  yarn.lock
Labels: dev-test

#3172 Feat/met 1963 drep details view
  package-lock.json
  package.json
  src/Routers.tsx
  src/commons/resources/icons/DisclaimerIcon.svg
  src/commons/resources/icons/dropdown.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/commons/utils/constants.ts
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/components/commons/DetailHeader/index.tsx
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/DrepDetail/styles.ts
  src/pages/NativeScriptsAndSC/TabNativeScripts.tsx
  src/types/bookmark.d.ts
  src/types/delegationPools.d.ts
  src/types/drep.d.ts
  src/types/stakeKey.d.ts
  yarn.lock
Labels: 1.1.0

#3200 feat: MET-1963 update fetch api
  src/components/GovernanceVotes/index.tsx
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3201 feat: MET-1963 update fetch api
  src/components/GovernanceVotes/index.tsx
  src/pages/DelegationDetail/index.tsx
Labels: 1.1.0

#3203 feat: MET-1963 update filter, map actiontype
  src/commons/utils/constants.ts
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3202 Feat/met 1957 pool details views
  src/commons/utils/api.ts
  src/commons/utils/helper.ts
  src/components/GovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3206 Feat/met 1963 drep details view dev
  src/components/GovernanceVotes/index.tsx
  src/components/share/styled.ts
  src/locales/en/translation.json
Labels: dev-test

#3208 feat: MET-1963 fix page size
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3207 fix: change modal metadata
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3209 Fix: fix bug MET 1957
  src/commons/utils/helper.ts
  src/components/GovernanceVotes/index.tsx
  src/components/GovernanceVotes/styles.ts
  src/locales/en/translation.json
Labels: dev-test

#3211 fix: fix bug pool details views
  src/commons/utils/helper.ts
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
  src/pages/NativeScriptsAndSC/styles.ts
Labels: dev-test

#3212 fix: add dark mode filter
  src/components/GovernanceVotes/index.tsx
  src/pages/NativeScriptsAndSC/styles.ts
Labels: dev-test

#3213 Fix/gov dev
  src/commons/resources/icons/history.svg
  src/commons/resources/index.ts
  src/components/GovernanceVotes/index.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
Labels: dev-test

#3205 Feat/met 1957 pool details views
  src/commons/utils/api.ts
  src/commons/utils/constants.ts
  src/commons/utils/helper.ts
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
Labels: 1.1.0

#3204 feat: MET-1963 update filter, map actiontype
  src/commons/resources/icons/history.svg
  src/commons/resources/index.ts
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/share/styled.ts
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
Labels: 1.1.0

#3214 Fix/anchor text
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3216 Fix/anchor text
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3218 fix: fix bug met 1957 pool details views
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/pages/NativeScriptsAndSC/styles.ts
Labels: dev-test

#3219 fix: fix responsive input
  src/components/GovernanceVotes/index.tsx
  src/locales/en/translation.json
Labels: dev-test
