Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-07, with the labels that each got.

#3662 Fix/drep detail bug UI test
  CHANGELOG.md
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/pages/address-detail.page.ts
  playwright/pages/block-detail.page.ts
  playwright/pages/blocks-dashboard.page.ts
  playwright/pages/epoch-detail.page.ts
  playwright/pages/epochs-dashboard.page.ts
  playwright/pages/pool-detail.page.ts
  playwright/pages/transaction-detail.page.ts
  playwright/tests/e2e/features/blocks.feature
  playwright/tests/e2e/features/epochs.feature
  playwright/tests/e2e/steps/blocks.steps.ts
  playwright/tests/e2e/steps/epochs.steps.ts
  src/components/BlockDetail/BlockOverview/index.tsx
  src/components/EpochDetail/EpochBlockList/index.tsx
  src/components/EpochDetail/EpochOverview/index.tsx
  src/components/TransactionListsFull/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailView/DetailViewBlock.tsx
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/components/commons/Table/index.tsx
  src/locales/en/translation.json
  src/pages/BlockList/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/Epoch/index.tsx
Labels: dev-test

#3664 fix: close button in protocol parameter
  src/components/ProtocolParameters/DetailViewGroupProtocol/DetailViewGroupProtocol.tsx
Labels: dev-test

#3667 fix: staking life cycle bug ui
  src/components/commons/Filter/styles.ts
Labels: dev-test

#3665 fix: close button in protocol parameter
  src/components/ProtocolParameters/DetailViewGroupProtocol/DetailViewGroupProtocol.tsx
Labels: 1.5.0

#3669 fix: show data overview chart
  src/components/ConstitutionalCommitteeDetail/Overview/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.5.0

#3670 Fix/show data test
  src/components/ConstitutionalCommitteeDetail/Overview/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3657 fix: UI missing horizontal line
  src/components/GovernanceVotes/OverallVote.tsx
Labels: 1.5.0

#3671 fix: staking life cycle bug ui
  src/components/commons/Filter/styles.ts
Labels: dev-test

#3675 fix: staking life cycle bug ui
  src/components/commons/CustomFilter/index.tsx
  src/components/commons/CustomFilter/styles.ts
  src/components/commons/Filter/styles.ts
Labels: dev-test

#3676 fix: scroll bar delegations
  src/components/TransactionDetail/TransactionMetadata/Delegations/styles.ts
Labels: dev-test

#3666 fix: staking life cycle bug ui
  src/components/commons/CustomFilter/index.tsx
  src/components/commons/CustomFilter/styles.ts
  src/components/commons/Filter/styles.ts
Labels: 1.5.0

#3659 fix: drep detail bug ui
  src/pages/DrepDetail/index.tsx
Labels: 1.5.0

#3684 fix: bug ui dreps
  src/components/DelegationPool/DelegationOverview/index.tsx
  src/components/DelegationPool/DelegationOverview/styles.ts
  src/components/Dreps/DrepsOverview/index.tsx
  src/components/Dreps/DrepsOverview/styles.ts
Labels: hold, dev-test

#3685 feat: MET-2104 add subtitle of dreps and pools
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/DelegationPool/DelegationList/styles.ts
  src/components/Dreps/DrepsList/index.tsx
  src/components/Dreps/DrepsList/styles.ts
  src/locales/en/translation.json
Labels: hold, dev-test

#3688 fix: bug ui Native Scripts & Smart Contracts
  src/components/DynamicEllipsisText/index.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
Labels: dev-test

#3690 feat: MET-2059 Ledger era
  src/components/ProtocolParameters/DetailViewGroupProtocol/styles.ts
  src/components/ProtocolParameters/ExplainerText.ts
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/pages/ProtocolParameter/index.tsx
Labels: dev-test

#3692 fix: MET-2059 Ledger era
  src/pages/ProtocolParameter/ExplainerTextModal.tsx
  src/pages/ProtocolParameter/index.tsx
Labels: dev-test

#3693 feat/met 2115 governance action overview
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/resources/icons/community-icon-dark.svg
  src/commons/resources/icons/community-icon-light.svg
  src/commons/resources/icons/team-icon-dark.svg
  src/commons/resources/icons/team-icon-light.svg
  src/commons/resources/icons/user-icon-dark.svg
  src/commons/resources/icons/user-icon-light.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/components/Overview/CardOverview/index.tsx
  src/components/Overview/CardOverview/styles.ts
  src/components/Overview/ChartOverview/index.tsx
  src/components/Overview/ChartOverview/styles.ts
  src/components/Overview/TabOverview/index.tsx
  src/components/Overview/TabOverview/styles.ts
  src/components/Overview/index.tsx
  src/components/Overview/styles.ts
  src/locales/en/translation.json
  src/pages/Overview/index.tsx
  src/pages/Overview/styles.ts
  src/types/governanceOverview.d.ts
Labels: dev-test

#3697 fix: bug ui Native Scripts & Smart Contracts
  src/pages/NativeScriptsAndSC/Card.tsx
Labels: dev-test

#3695 fix: remove line in table
  src/components/Overview/TabOverview/styles.ts
Labels: dev-test

#3698 fix/color label in chart
  src/components/Overview/CardOverview/index.tsx
  src/components/Overview/ChartOverview/index.tsx
Labels: dev-test

#3699 fix: MET-2059 background tooltip
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
Labels: dev-test

#3700 fix: bug UI and mapping type status
  src/commons/utils/constants.ts
  src/components/Overview/CardOverview/index.tsx
  src/components/Overview/CardOverview/styles.ts
  src/components/Overview/TabOverview/index.tsx
  src/components/Overview/TabOverview/styles.ts
  src/locales/en/translation.json
  src/pages/Overview/styles.ts
Labels: dev-test

#3696 feat: MET-2104 update subtitle
  src/components/DelegationPool/DelegationList/styles.ts
  src/components/Dreps/DrepsList/styles.ts
  src/locales/en/translation.json
  src/pages/DelegationPools/index.tsx
  src/pages/Dreps/index.tsx
Labels: dev-test

#3702 fix: update coding
  src/components/ConstitutionalCommittees/index.tsx
  src/components/Overview/CardOverview/styles.ts
  src/components/Overview/ChartOverview/index.tsx
  src/components/Overview/TabOverview/index.tsx
  src/components/Overview/TabOverview/styles.ts
  src/components/Overview/index.tsx
  src/components/Overview/styles.ts
  src/pages/ConstitutionalCommittees/index.tsx
  src/pages/Overview/index.tsx
Labels: dev-test

#3703 fix: update color line table
  src/components/Overview/ChartOverview/index.tsx
  src/components/Overview/TabOverview/index.tsx
Labels: dev-test

#3689 feat: MET-2059 Ledger era
  src/components/ProtocolParameters/DetailViewGroupProtocol/styles.ts
  src/components/ProtocolParameters/ExplainerText.ts
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/pages/ProtocolParameter/ExplainerTextModal.tsx
  src/pages/ProtocolParameter/index.tsx
  src/pages/ProtocolParameter/styles.ts
Labels: 1.6.0

#3706 fix: status chart
  src/components/Overview/ChartOverview/index.tsx
Labels: dev-test

#3709 fix: display label chart
  src/components/Overview/ChartOverview/index.tsx
Labels: dev-test

#3710 fix: fix link card
  src/components/Overview/CardOverview/index.tsx
Labels: dev-test

#3707 fix: status chart
  src/components/Overview/ChartOverview/index.tsx
Labels: 1.6.0

#3708 fix: fix label chart
  src/components/Overview/CardOverview/index.tsx
  src/components/Overview/ChartOverview/index.tsx
Labels: 1.6.0

#3686 feat: MET-2104 add subtitle of dreps and pools
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/DelegationPool/DelegationList/styles.ts
  src/components/Dreps/DrepsList/index.tsx
  src/components/Dreps/DrepsList/styles.ts
  src/locales/en/translation.json
  src/pages/DelegationPools/index.tsx
  src/pages/Dreps/index.tsx
Labels: 1.6.0

#3687 fix: bug ui Native Scripts & Smart Contracts
  src/components/DynamicEllipsisText/index.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
Labels: 1.6.0

#3681 fix: bug ui dreps and pools
  src/components/DelegationPool/DelegationOverview/index.tsx
  src/components/Dreps/DrepsOverview/index.tsx
Labels: 1.6.0

#3683 fix: bug ui delegations
  src/components/TransactionDetail/TransactionMetadata/Delegations/styles.ts
Labels: 1.6.0

#3712 chore: update version release
  .github/workflows/release.yaml
  package-lock.json
  package.json
Labels: 1.6.0

#3718 Fix/chart missing line test
  .github/workflows/release.yaml
  package-lock.json
  package.json
  src/components/Home/Trending/TransactionChart/index.tsx
Labels: dev-test

#3721 fix: popup address sc detail
  src/pages/SmartContractDetail/ViewAddressesModal.tsx
Labels: hold

#3716 fix: chart missing line
  src/components/Home/Trending/TransactionChart/index.tsx
Labels: 1.6.0

#3713 fix: slot number in epoch page wrong
  src/components/commons/DetailView/DetailViewEpoch.tsx
Labels: 1.6.0

#3653 test: MET-2227 add automation test for transaction overview
  playwright/api/call-koios/koios.api.ts
  playwright/api/dtos/transactionInformation.dto.ts
  playwright/helpers/endpoints.ts
  playwright/pages/address-detail.page.ts
  playwright/pages/blocks-dashboard.page.ts
  playwright/pages/transaction-detail.page.ts
  playwright/pages/transaction-overview.page.ts
  playwright/tests/e2e/features/transaction-overview.feature
  playwright/tests/e2e/steps/transactions-overview.steps.ts
  src/components/TransactionLists/index.tsx
  src/components/commons/DetailView/DetailViewTransaction.tsx
Labels: Automation Test

#3719 Test/met 2243 create automation test for pools page
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/api/dtos/blockfrostPoolInformation.dto.ts
  playwright/helpers/endpoints.ts
  playwright/pages/block-detail.page.ts
  playwright/pages/pool.page.ts
  playwright/pages/stake-detail.page.ts
  playwright/tests/e2e/features/pools.feature
  playwright/tests/e2e/steps/pools.steps.ts
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/DelegationPool/DelegationOverview/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: Automation Test

#3723 fix: sc detail scroll associated
  src/pages/SmartContractDetail/TabAssociated.tsx
Labels: hold, dev-test

#3728 fix: transaction Staking Delegation Lifecycle
  src/components/StakingLifeCycle/DelegatorLifecycle/ADATransferModal/UserInfo.tsx
Labels: hold, 1.7.0

#3727 fix: transaction Staking Delegation Lifecycle
  src/components/StakingLifeCycle/DelegatorLifecycle/ADATransferModal/UserInfo.tsx
Labels: dev-test

#3730 feat/met-2246 number of nodes in the system
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/resources/icons/menus/networkMonitoring.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/components/NetworkMonitoring/RegisteredStakepools/index.tsx
  src/components/NetworkMonitoring/RegisteredStakepools/styles.ts
  src/components/NetworkMonitoring/index.tsx
  src/locales/en/translation.json
  src/pages/NetworkMonitoring/index.tsx
  src/pages/NetworkMonitoring/styles.ts
Labels: dev-test

#3733 Feat/met 2245 number of transactions per day
  src/components/NetworkMonitoring/TransactionNumberChart/index.tsx
  src/components/NetworkMonitoring/TransactionNumberChart/styles.ts
  src/components/NetworkMonitoring/index.tsx
Labels: dev-test

#3734 fix: update coding
  src/components/NetworkMonitoring/RegisteredStakepools/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/pages/NetworkMonitoring/index.tsx
Labels: dev-test

#3735 fix: update coding
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/pages/NetworkMonitoring/index.tsx
Labels: dev-test

#3731 feat: met 2246 number of nodes in the system
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/resources/icons/menus/networkMonitoring.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/components/NetworkMonitoring/RegisteredStakepools/index.tsx
  src/components/NetworkMonitoring/RegisteredStakepools/styles.ts
  src/components/NetworkMonitoring/index.tsx
  src/locales/en/translation.json
  src/pages/NetworkMonitoring/index.tsx
  src/pages/NetworkMonitoring/styles.ts
Labels: 1.7.0

#3738 Feat/met 2247 block distribution per epoch chart dev test
  src/commons/utils/api.ts
  src/components/NetworkMonitoring/BlockPropagation/index.tsx
  src/components/NetworkMonitoring/BlockPropagation/styles.ts
  src/components/NetworkMonitoring/index.tsx
Labels: dev-test

#3739 fix: MET-2245 Number of transaction per day
  src/components/NetworkMonitoring/TransactionNumberChart/styles.ts
Labels: dev-test

#3740 fix: scroll stake address history
  src/components/StakeDetail/StakeTab/Tabs/StakeHistoryTab.tsx
Labels: dev-test

#3741 fix: add no record when call data error
  src/components/NetworkMonitoring/BlockPropagation/index.tsx
  src/components/NetworkMonitoring/RegisteredStakepools/index.tsx
Labels: dev-test

#3742 fix: update title
  src/components/NetworkMonitoring/TransactionNumberChart/styles.ts
Labels: dev-test

#3737 feat: MET-2247 block distribution per epoch chart
  src/commons/utils/api.ts
  src/components/NetworkMonitoring/BlockPropagation/index.tsx
  src/components/NetworkMonitoring/BlockPropagation/styles.ts
  src/components/NetworkMonitoring/RegisteredStakepools/index.tsx
  src/components/NetworkMonitoring/index.tsx
Labels: 1.7.0

#3744 feat: MET-2276 Fetch and index data reference by anchor link
  src/components/Overview/TabOverview/index.tsx
  src/types/governanceOverview.d.ts
Labels: dev-test
