Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-06, with the labels that each got.

#3501 feat: MET-2023 add new SC virtual in trx detail
  src/commons/resources/icons/governance.svg
  src/commons/resources/index.ts
  src/components/Contracts/ContractDetail.tsx
  src/components/Contracts/Proposingviews/index.tsx
  src/components/Contracts/Votingviews/index.tsx
  src/components/Contracts/common/ContractItem.tsx
  src/components/Contracts/common/DataCardEllipsisText.tsx
  src/components/Contracts/common/GovernanceActionCard.tsx
  src/components/Contracts/common/ViewGorvernanceVotes.tsx
  src/components/Contracts/common/ViewGovenanceProposing.tsx
  src/components/Contracts/common/styles.ts
  src/components/Contracts/modals/ProposingOutputModal.tsx
  src/components/Contracts/modals/VotingOutputModal.tsx
  src/components/GovernanceVotes/OverviewVote.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/TransactionDetail/TransactionMetadata/index.tsx
  src/components/commons/InfoSolidIcon/index.tsx
  src/components/commons/ViewBlocks/OutputVoting.tsx
  src/components/commons/ViewBlocks/styles.ts
  src/locales/en/translation.json
  src/types/transactions.d.ts
Labels: 1.4.0

#3551 fix: MET-2023 Identity new SC
  src/components/Contracts/common/styles.ts
  src/components/Contracts/modals/RedeemerModal.tsx
Labels: dev-test

#3554 fix: MET-2052 update code pool filter
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3544 feat/met 2049 hide time and filter table
  src/commons/hooks/useFetch.ts
  src/commons/hooks/useFetchList.ts
  src/commons/resources/icons/fetch-data-err-dark.svg
  src/commons/resources/icons/fetch-data-err-light.svg
  src/commons/resources/index.ts
  src/components/ContractDetail/ContractDetailContent/TokenTransaction/index.tsx
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/Dreps/DrepsList/index.tsx
  src/components/EpochDetail/EpochBlockList/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/PolicyDetail/PolicyTable/index.tsx
  src/components/ReportGeneratedStakingDetail/StakeyTabs/DelegationTab.tsx
  src/components/ReportGeneratedStakingDetail/StakeyTabs/RewardsDistributionTab.tsx
  src/components/ReportGeneratedStakingDetail/StakeyTabs/WithdrawalHistoryTab.tsx
  src/components/TabularView/StakeTab/Tabs/DelegationTab.tsx
  src/components/TabularView/StakeTab/Tabs/RewardsDistributionTab.tsx
  src/components/TabularView/StakeTab/Tabs/WithdrawalHistoryTab.tsx
  src/components/TokenDetail/TokenTableData/TokenMinting.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TopAddresses/ByADABalance/index.tsx
  src/components/TopAddresses/ByAmountStaked/index.tsx
  src/components/TransactionLists/index.tsx
  src/components/commons/FetchDataErr/index.tsx
  src/components/commons/Table/index.tsx
  src/pages/BlockList/index.tsx
  src/pages/ContractList/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/Epoch/index.tsx
  src/pages/InstantRewards/index.tsx
  src/pages/NativeScriptsAndSC/TabNativeScripts.tsx
  src/pages/NativeScriptsAndSC/TabSmartContracts.tsx
  src/pages/ProtocolParameter/index.tsx
  src/pages/RegistrationPools/index.tsx
  src/pages/Stake/index.tsx
  src/pages/StakeDelegations/index.tsx
  src/pages/StakingLifecycle/index.tsx
  src/pages/Token/index.tsx
  src/types/table.d.ts
Labels: 1.4.0

#3538 fix/fix data displayed incorrect pool detail
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
Labels: 1.4.0

#3548 fix/incorrect time update drep detail
  src/pages/DrepDetail/index.tsx
Labels: 1.4.0

#3558 fix: revert code
  src/components/commons/CardGovernanceVotes/index.tsx
Labels: dev-test

#3553 fix: MET-2152 pools filters update coding
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: 1.4.0

#3556 fix: delete tooltip
  src/components/commons/CardGovernanceVotes/index.tsx
Labels: 1.4.0

#3559 fix: MET-2023 Identify new SC
  src/components/Contracts/Proposingviews/index.tsx
  src/components/Contracts/common/styles.ts
Labels: dev-test

#3550 Feat/met 2023 identify new sc purposes and visualization patterns
  src/components/Contracts/Proposingviews/index.tsx
  src/components/Contracts/common/styles.ts
  src/components/Contracts/modals/RedeemerModal.tsx
Labels: 1.4.0

#3562 fix: MET-2023 Identify new SC
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3560 fix: MET-2150 BUG UI
  src/components/GovernanceVotes/index.tsx
Labels: 1.4.0

#3564 fix: reponsive notification in table
  src/components/commons/FetchDataErr/index.tsx
Labels: dev-test

#3541 fix: DrepId bug ui mobile
  src/components/DynamicEllipsisText/index.tsx
Labels: 1.4.0

#3561 fix: MET-2023 Identify new SC
  src/components/GovernanceVotes/index.tsx
Labels: 1.4.0

#3563 fix/reponsive notification in table
  src/components/commons/FetchDataErr/index.tsx
Labels: 1.4.0

#3568 fix: drep details bug ui
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3570 fix: MET-2023 Indentify new SC
  src/components/TransactionDetail/TransactionMetadata/index.tsx
Labels: dev-test

#3573 fix: native and smart contract bug ui
  src/pages/NativeScriptsAndSC/index.tsx
  src/pages/NativeScriptsAndSC/styles.ts
Labels: dev-test

#3574 fix: scrool bar in compiled code
  src/components/Contracts/common/styles.ts
Labels: dev-test

#3578 Fix/met 2055 remove flag na governance
  docker-compose.yml
  env.global.tmp.js
  src/commons/utils/constants.ts
  src/components/GovernanceVotes/OverallVote.tsx
  vite.config.ts
Labels: 1.3.0

#3577 fix: bug ui display token id not inline
  src/components/commons/DetailHeader/styles.ts
Labels: dev-test

#3572 fix: native and smart contract bug ui
  src/pages/NativeScriptsAndSC/index.tsx
  src/pages/NativeScriptsAndSC/styles.ts
Labels: 1.4.0

#3575 fix: scrool bar in compiled code
  src/components/Contracts/common/styles.ts
Labels: 1.4.0

#3565 fix: display no record in stake address detail
  src/pages/StakeDetail/index.tsx
Labels: 1.4.0

#3576 fix: bug ui display token id not inline
  src/components/commons/DetailHeader/styles.ts
Labels: 1.4.0

#3583 Feat/cc view dev test
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/resources/icons/CCActiveMembers.svg
  src/commons/resources/icons/CCCurentState.svg
  src/commons/resources/icons/CCGorvernanceVote.svg
  src/commons/resources/icons/CCGovernanceVotes.svg
  src/commons/resources/icons/CCHistoryStatus.svg
  src/commons/resources/icons/CCLastChange.svg
  src/commons/resources/icons/CCProposalPolicy.svg
  src/commons/resources/icons/CCThreshold.svg
  src/commons/resources/icons/CCUpcomingChange.svg
  src/commons/resources/icons/CClistMembers.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/components/ConstitutionalCommittees/Overrall/index.tsx
  src/components/ConstitutionalCommittees/Overrall/styles.tsx
  src/components/ConstitutionalCommittees/Tabs/Members/index.tsx
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/index.tsx
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/style.tsx
  src/components/ConstitutionalCommittees/Tabs/index.tsx
  src/components/ConstitutionalCommittees/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Tabular/index.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/index.tsx
  src/components/commons/Layout/Footer/index.tsx
  src/locales/en/translation.json
  src/pages/ConstitutionalCommittees/index.tsx
  src/pages/ConstitutionalCommittees/styles.ts
  src/pages/NativeScriptsAndSC/ContractHeader.tsx
  src/pages/NativeScriptsAndSC/styles.ts
Labels: dev-test

#3584 Feat/met 2053 d rep details view test
  src/components/GovernanceVotes/OverviewVote.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3586 Fix/cc view test
  src/commons/menus.ts
  src/commons/resources/icons/governanceHome.svg
  src/commons/resources/index.ts
  src/components/ConstitutionalCommittees/Overrall/index.tsx
Labels: dev-test

#3507 test: MET-2188 add automation test for epoch
  playwright/pages/epoch-detail.page.ts
  playwright/pages/epochs-dashboard.page.ts
  playwright/tests/e2e/features/epochs.feature
  playwright/tests/e2e/steps/epochs.steps.ts
  src/components/EpochDetail/EpochBlockList/index.tsx
  src/components/EpochDetail/EpochOverview/index.tsx
  src/components/TransactionListsFull/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/components/commons/Table/index.tsx
  src/locales/en/translation.json
  src/pages/Epoch/index.tsx
Labels: Automation Test

#3549 test: MET-2190 add automation test for block
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/pages/address-detail.page.ts
  playwright/pages/block-detail.page.ts
  playwright/pages/blocks-dashboard.page.ts
  playwright/pages/epoch-detail.page.ts
  playwright/pages/pool-detail.page.ts
  playwright/pages/transaction-detail.page.ts
  playwright/tests/e2e/features/blocks.feature
  playwright/tests/e2e/steps/blocks.steps.ts
  src/components/BlockDetail/BlockOverview/index.tsx
  src/components/TransactionListsFull/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailView/DetailViewBlock.tsx
  src/locales/en/translation.json
  src/pages/BlockList/index.tsx
Labels: Automation Test

#3594 fix: native script detail
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: dev-test

#3592 feat: DReps table missing Governance Participation Rate column in tab…
  src/commons/resources/icons/participation-rate.svg
  src/commons/resources/index.ts
  src/components/Dreps/DrepFilter/index.tsx
  src/components/Dreps/DrepsList/index.tsx
  src/locales/en/translation.json
  src/types/drep.d.ts
Labels: dev-test

#3590 fix: MET-2053 Drep Detail View
  src/components/CIPComplianceModal/styles.ts
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3598 fix: not on a straight line overall vote
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3596 feat: MET-2128 Protocol Parameters page into groups
  src/commons/resources/icons/protect-icon-dark.svg
  src/commons/resources/icons/protect-icon.svg
  src/commons/resources/index.ts
  src/components/ProtocolParameters/DetailViewGroupProtocol/DetailViewGroupProtocol.tsx
  src/components/ProtocolParameters/DetailViewGroupProtocol/styles.ts
  src/components/ProtocolParameters/ExplainerText.ts
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/components/ProtocolParameters/GroupProtocolParameters/styles.ts
  src/components/ProtocolParameters/ProtocolHeader/index.tsx
  src/components/ProtocolParameters/ProtocolHeader/styles.ts
  src/components/commons/Card/index.tsx
  src/locales/en/translation.json
  src/pages/ProtocolParameter/index.tsx
  src/pages/ProtocolParameter/styles.ts
  src/types/protocol.d.ts
Labels: dev-test

#3599 fix: update func format time
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
Labels: dev-test

#3602 Fix/remove bracket 1 4
  docker-compose.yml
  env.global.tmp.js
  src/commons/utils/constants.ts
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
  src/pages/DelegationDetail/index.tsx
  vite.config.ts
Labels: hold, 1.4.0

#3603 Fix/remove bracket 1 4
  docker-compose.yml
  env.global.tmp.js
  src/commons/utils/constants.ts
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
  src/pages/DelegationDetail/index.tsx
  vite.config.ts
Labels: hold, 1.5.0

#3604 Fix/remove bracket
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3605 fix: fix table in Abstain Information
  src/components/CIPComplianceModal/styles.ts
Labels: dev-test

#3608 feat: update coding protocol parameters
  src/components/ProtocolParameters/DetailViewGroupProtocol/styles.ts
  src/components/ProtocolParameters/ExplainerText.ts
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/components/ProtocolParameters/GroupProtocolParameters/styles.ts
  src/components/commons/InfoSolidIcon/index.tsx
  src/pages/ProtocolParameter/index.tsx
Labels: dev-test

#3607 fix: token-details-bug-ui
  src/components/TokenDetail/TokenTableData/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/SmartContractDetail/ContractTabs.tsx
Labels: dev-test

#3609 fix: token-detail-bug-ui
  src/components/StakeDetail/StakeTab/index.tsx
Labels: dev-test

#3580 feat: MET-2053 Drep Detail View
  src/components/CIPComplianceModal/styles.ts
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/GovernanceVotes/OverviewVote.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/pages/DrepDetail/index.tsx
Labels: 1.5.0

#3597 fix: not on a straight line overall vote
  src/components/GovernanceVotes/OverallVote.tsx
Labels: 1.5.0

#3593 Fix/native scripts details
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: 1.5.0

#3612 Fix/view cc
  src/commons/utils/api.ts
  src/commons/utils/constants.ts
  src/components/ConstitutionalCommittees/Overrall/index.tsx
  src/components/ConstitutionalCommittees/Tabs/Members/index.tsx
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/index.tsx
  src/components/ConstitutionalCommittees/Tabs/index.tsx
  src/components/ConstitutionalCommittees/index.tsx
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/GovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/types/committee.d.ts
  src/types/drep.d.ts
Labels: dev-test

#3613 fix: add N/a
  src/components/ConstitutionalCommittees/Overrall/index.tsx
Labels: dev-test

#3614 Fix/cc detail
  src/commons/hooks/useScreen.ts
  src/commons/utils/api.ts
  src/components/ConstitutionalCommitteeDetail/Overview/index.tsx
  src/components/ConstitutionalCommitteeDetail/Tabs/index.tsx
  src/components/ConstitutionalCommitteeDetail/index.tsx
  src/components/ConstitutionalCommittees/Overrall/index.tsx
  src/components/ConstitutionalCommittees/Tabs/Members/index.tsx
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailHeader/styles.ts
  src/locales/en/translation.json
  src/types/committee.d.ts
  src/types/stakeKey.d.ts
Labels: dev-test

#3617 fix: MET-2029 update cc detail overview:
  src/commons/utils/api.ts
  src/components/ConstitutionalCommitteeDetail/Overview/index.tsx
  src/components/ConstitutionalCommitteeDetail/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3616 feat: MET-2220 Transaction history from genesis
  src/components/Home/Trending/TransactionChart/index.tsx
  src/components/Home/Trending/TransactionChart/styles.ts
  src/locales/en/translation.json
Labels: dev-test

#3619 feat: update UI
  src/commons/hooks/useFetchList.ts
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/index.tsx
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3618 feat: MET-2220 Transaction history from genesis
  src/components/Home/Trending/TransactionChart/index.tsx
Labels: dev-test

#3621 Fix/cc detail resolve
  src/components/ConstitutionalCommitteeDetail/Overview/index.tsx
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3622 fix: MET-2029 show gov vote detail
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3624 feat: MET-2029 update UI
  src/components/ConstitutionalCommitteeDetail/Overview/index.tsx
  src/components/ConstitutionalCommittees/Overrall/index.tsx
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3625 fix: update tooltip color
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#3626 fix: update clear text search
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3627 fix: staking lifecycle bug ui
  src/components/ReportGeneratedStakingDetail/index.tsx
Labels: dev-test

#3628 fix: update filter
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/index.tsx
Labels: dev-test

#3582 feat: MET-2028 add view constitutional committee
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/resources/icons/CCActiveMembers.svg
  src/commons/resources/icons/CCCurentState.svg
  src/commons/resources/icons/CCGorvernanceVote.svg
  src/commons/resources/icons/CCGovernanceVotes.svg
  src/commons/resources/icons/CCHistoryStatus.svg
  src/commons/resources/icons/CCLastChange.svg
  src/commons/resources/icons/CCProposalPolicy.svg
  src/commons/resources/icons/CCThreshold.svg
  src/commons/resources/icons/CCUpcomingChange.svg
  src/commons/resources/icons/CClistMembers.svg
  src/commons/resources/icons/governanceHome.svg
  src/commons/resources/index.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/commons/utils/constants.ts
  src/components/ConstitutionalCommittees/Overrall/index.tsx
  src/components/ConstitutionalCommittees/Overrall/styles.tsx
  src/components/ConstitutionalCommittees/Tabs/Members/index.tsx
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/index.tsx
  src/components/ConstitutionalCommittees/Tabs/StatusHistory/style.tsx
  src/components/ConstitutionalCommittees/Tabs/index.tsx
  src/components/ConstitutionalCommittees/index.tsx
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/Tabular/index.tsx
  src/components/StakingLifeCycle/SPOLifecycle/Tablular/index.tsx
  src/components/commons/Layout/Footer/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/locales/en/translation.json
  src/pages/ConstitutionalCommittees/index.tsx
  src/pages/ConstitutionalCommittees/styles.ts
  src/pages/NativeScriptsAndSC/ContractHeader.tsx
  src/pages/NativeScriptsAndSC/styles.ts
  src/types/committee.d.ts
  src/types/drep.d.ts
Labels: 1.5.0

#3629 feat: add tooltip
  src/components/ProtocolParameters/DetailViewGroupProtocol/DetailViewGroupProtocol.tsx
  src/components/ProtocolParameters/DetailViewGroupProtocol/styles.ts
  src/components/ProtocolParameters/ExplainerText.ts
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/components/ProtocolParameters/GroupProtocolParameters/styles.ts
  src/pages/ProtocolParameter/index.tsx
Labels: dev-test

#3630 fix: update truncate text
  src/components/ProtocolParameters/ExplainerText.ts
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/components/commons/Card/index.tsx
Labels: dev-test

#3631 fix: token details bug ui
  src/components/ReportGeneratedPoolDetail/index.tsx
Labels: dev-test

#3610 fix: incorrect pool name and distance drep detaill
  src/components/DynamicEllipsisText/index.tsx
  src/components/GovernanceVotes/OverallVote.tsx
Labels: 1.5.0

#3632 feat: MET-2215 update feild
  src/components/Dreps/DrepsList/index.tsx
  src/types/drep.d.ts
Labels: dev-test

#3633 fix: MET-2215 update icon
  src/components/Dreps/DrepFilter/index.tsx
Labels: dev-test

#3634 feat: MET-2029 add title
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3636 fix: add card
  src/components/ProtocolParameters/ExplainerText.ts
  src/pages/ProtocolParameter/index.tsx
Labels: dev-test

#3591 feat: DReps table missing Governance Participation Rate column in tab…
  src/commons/resources/icons/participation-rate.svg
  src/commons/resources/index.ts
  src/components/Dreps/DrepFilter/index.tsx
  src/components/Dreps/DrepsList/index.tsx
  src/locales/en/translation.json
  src/types/drep.d.ts
Labels: 1.5.0

#3615 feat: MET-2220 Transaction history from genesis
  src/components/Home/Trending/TransactionChart/index.tsx
  src/components/Home/Trending/TransactionChart/styles.ts
  src/locales/en/translation.json
Labels: 1.5.0

#3637 feat: MET-2029 update icon
  src/components/ConstitutionalCommitteeDetail/Overview/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3638 feat: MET-2029 update icon
  src/components/ConstitutionalCommitteeDetail/Overview/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.5.0

#3639 fix: MET-2029 remove bookmark drep
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3640 fix: MET-2029 remove bookmark drep
  src/pages/DrepDetail/index.tsx
Labels: 1.5.0

#3643 Feat/met 2220 transaction history from genesis test
  src/components/GovernanceVotes/OverallVote.tsx
  src/components/Home/Trending/TransactionChart/index.tsx
  src/components/Home/Trending/TransactionChart/styles.ts
Labels: dev-test

#3644 fix: remove card
  src/pages/ProtocolParameter/index.tsx
Labels: dev-test

#3646 feat/met 2128 resolve conflic dev test
  src/components/ProtocolParameters/DetailViewGroupProtocol/DetailViewGroupProtocol.tsx
  src/components/ProtocolParameters/DetailViewGroupProtocol/styles.ts
  src/components/ProtocolParameters/ExplainerText.ts
Labels: dev-test

#3647 fix: clear text
  src/components/ProtocolParameters/ExplainerText.ts
Labels: dev-test

#3650 fix: fix text
  src/components/ProtocolParameters/ExplainerText.ts
Labels: dev-test

#3595 feat: MET-2128 Protocol Parameters page into groups
  src/commons/resources/icons/protect-icon-dark.svg
  src/commons/resources/icons/protect-icon.svg
  src/commons/resources/index.ts
  src/components/ProtocolParameters/DetailViewGroupProtocol/DetailViewGroupProtocol.tsx
  src/components/ProtocolParameters/DetailViewGroupProtocol/styles.ts
  src/components/ProtocolParameters/ExplainerText.ts
  src/components/ProtocolParameters/GroupProtocolParameters/GroupProtocolParameters.tsx
  src/components/ProtocolParameters/GroupProtocolParameters/styles.ts
  src/components/ProtocolParameters/ProtocolHeader/index.tsx
  src/components/ProtocolParameters/ProtocolHeader/styles.ts
  src/components/commons/Card/index.tsx
  src/components/commons/InfoSolidIcon/index.tsx
  src/locales/en/translation.json
  src/pages/ProtocolParameter/index.tsx
  src/pages/ProtocolParameter/styles.ts
  src/types/protocol.d.ts
Labels: 1.5.0

#3652 fix: fix display filter maxGovParticipationRate drep and pool
  src/commons/utils/helper.ts
  src/components/Dreps/DrepFilter/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3649 fix: fix cursor poolId an poolhash
  src/components/DelegationDetail/DelegationDetailInfo/styles.ts
Labels: 1.5.0

#3651 fix: fix display filter maxGovParticipationRate drep and pool
  src/commons/utils/helper.ts
  src/components/Dreps/DrepFilter/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: 1.5.0

#3606 Fix/token details bug UI
  src/components/ReportGeneratedPoolDetail/index.tsx
  src/components/ReportGeneratedStakingDetail/index.tsx
  src/components/StakeDetail/StakeTab/index.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/SmartContractDetail/ContractTabs.tsx
Labels: 1.5.0
