Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-04, with the labels that each got.

#3223 feat: MET-1963 update show action type
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3224 feat: fix anchor text
  src/components/GovernanceVotes/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3226 fix: fix text anchor
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3225 Feat/met 1957 pools details views
  src/commons/resources/icons/repeatVote.svg
  src/commons/resources/index.ts
  src/components/GovernanceVotes/index.tsx
  src/components/GovernanceVotes/styles.ts
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/styles.ts
  src/components/commons/CopyButton/index.tsx
  src/locales/en/translation.json
  src/pages/NativeScriptsAndSC/styles.ts
Labels: 1.1.0

#3228 Feat/met 1963 drep details view
  src/components/commons/Table/index.tsx
  src/locales/en/translation.json
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.1.0

#3231 fix: MET-1963 disnable filter button
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3171 fix: MET-1960 update pool list
  src/components/DelegationPool/DelegationList/index.tsx
  src/locales/en/translation.json
  src/types/delegationPools.d.ts
Labels: 1.1.0

#3232 fix: MET-1963 update pass index trx in api
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3233 fix: fix bug responsive MET 1957
  src/components/GovernanceVotes/index.tsx
  src/components/GovernanceVotes/styles.ts
  src/components/commons/DetailHeader/index.tsx
  src/locales/en/translation.json
  src/pages/NativeScriptsAndSC/styles.ts
Labels: dev-test

#3237 fix: MET-1963 text align tooltip
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3238 fix: add id hash drep pool
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3240 fix: add id hash drep pool
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3241 Fix/go back list govenance
  src/components/GovernanceVotes/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3244 Fix/decode v3 test
  package-lock.json
  src/components/Contracts/UPLCTree/index.tsx
  src/components/Contracts/common/CompiledCodeDataCard.tsx
  yarn.lock
Labels: dev-test

#3229 fix: MET-1963 update UI
  src/commons/resources/icons/multiyes.svg
  src/commons/resources/index.ts
  src/components/DelegationDetail/DelegationDetailInfo/styles.ts
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
  src/pages/NativeScriptsAndSC/styles.ts
Labels: 1.1.0

#3235 fix: fix bug responsive MET 1957
  src/components/GovernanceVotes/index.tsx
  src/components/GovernanceVotes/styles.ts
  src/components/commons/DetailHeader/index.tsx
  src/pages/NativeScriptsAndSC/styles.ts
Labels: 1.1.0

#3246 fix: fix multiple icon and percent chart
  src/commons/resources/icons/multiNoneIcon.svg
  src/commons/resources/index.ts
  src/commons/utils/helper.ts
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
Labels: dev-test

#3249 chore: remove percent
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3250 fix: fix bug ui filter
  src/components/GovernanceVotes/index.tsx
  src/components/GovernanceVotes/styles.ts
  src/pages/DelegationDetail/styles.ts
  src/themes/palette.ts
Labels: dev-test

#3247 fix: fix percent and icon multiple
  src/commons/resources/icons/multiNoneIcon.svg
  src/commons/resources/index.ts
  src/commons/utils/helper.ts
  src/components/GovernanceVotes/index.tsx
  src/components/GovernanceVotes/styles.ts
  src/components/commons/CardGovernanceVotes/index.tsx
  src/pages/DelegationDetail/styles.ts
  src/themes/palette.ts
Labels: 1.1.0

#3251 fix: decode uplc crash app
  src/components/Contracts/UPLCTree/index.tsx
  src/components/Contracts/common/CompiledCodeDataCard.tsx
Labels: dev-test

#3243 fix: decpode uplc plutus v3
  src/components/Contracts/UPLCTree/index.tsx
  src/components/Contracts/common/CompiledCodeDataCard.tsx
Labels: 1.1.0

#3252 Fix: fix UI responsive drep
  src/components/GovernanceVotes/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3253 fix: fix ui responsive drep MET 1957
  src/components/GovernanceVotes/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.1.0

#3255 chore: change title gov
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3254 chore: change title gov
  src/pages/DelegationDetail/index.tsx
Labels: 1.1.0

#3259 fix: MET-2034 update text
  src/locales/en/translation.json
  src/pages/Refference/FAQ.tsx
Labels: 1.1.0

#3261 fix: fix bug ui filter
  src/components/GovernanceVotes/index.tsx
  src/components/GovernanceVotes/styles.ts
  src/components/commons/CardGovernanceVotes/index.tsx
Labels: dev-test

#3262 Fix/met 1957 update UI
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3264 fix: MET-1957 update ui
  src/components/GovernanceVotes/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3265 fix: MET-1953 update filter governance
  src/components/GovernanceVotes/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailHeader/styles.ts
  src/locales/en/translation.json
  src/types/drep.d.ts
  src/types/stakeKey.d.ts
Labels: dev-test

#3266 fix: fix spacing textarea
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3267 fix: MET-1957 fix text overflow
  src/components/GovernanceVotes/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3257 fix: fix bug common MET 1957
  src/components/GovernanceVotes/index.tsx
  src/components/GovernanceVotes/styles.ts
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/CopyButton/index.tsx
  src/components/commons/Layout/Sidebar/index.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.1.0

#3263 fix: MET-1957 update filter
  src/components/GovernanceVotes/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailHeader/styles.ts
  src/locales/en/translation.json
  src/pages/DrepDetail/index.tsx
  src/types/drep.d.ts
  src/types/stakeKey.d.ts
Labels: 1.1.0

#3268 chore: remove duplicate css hashname
  src/components/GovernanceVotes/styles.ts
Labels: dev-test

#3269 Fix : checked value option filter
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3270 Feat/met 1957 pool details view
  src/components/GovernanceVotes/index.tsx
Labels: 1.1.0

#3272 fix: fix pool name and display date when filter
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3274 Fix/add percent for drep chart
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#3271 fix: MET-2025 fix cypress test fail
  cypress/e2e/DelegatorLifecycleTests.cy.ts
  cypress/e2e/ProtocolParamTests.cy.ts
  cypress/e2e/SmartcontractDetail.cy.ts
  cypress/e2e/contracts.cy.ts
  cypress/e2e/delegationPool.cy.ts
  cypress/e2e/deregistrationScreen/DeregistrationScreenTest.cy.ts
  cypress/e2e/epochs.cy.ts
  cypress/e2e/policy.cy.ts
  cypress/e2e/scenario/ContractScenario/userInteractWithContractTab.cy.ts
  cypress/e2e/spoTabularView/PoolGeneralInformationTest.cy.ts
  cypress/e2e/spoTabularView/SPOTabularViewTest.cy.ts
  cypress/e2e/spoTabularView/TransactionTableTest.cy.ts
  cypress/e2e/stakeKeyTabularView/StakeKeyTabularViewTest.cy.ts
  cypress/e2e/stakingLifecycle/DeregistrationListTest.cy.ts
  cypress/e2e/transactions.cy.ts
  package-lock.json
  package.json
  src/components/CIPComplianceModal/CIP25Modal.tsx
  src/pages/DelegatorLifecycle/index.tsx
  src/pages/SPOLifecycle/index.tsx
Labels: 1.1.0

#3275 Fix: clear date when use clearable
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CustomFilter/DateRangeModal.tsx
Labels: dev-test

#3276 fix: check disable and active filter
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3277 fix: display full data JsonViewer
  src/components/GovernanceVotes/index.tsx
Labels: dev-test

#3273 feat: MET 1957 pool details view
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CustomFilter/DateRangeModal.tsx
  src/pages/DrepDetail/index.tsx
Labels: 1.1.0

#3279 Fix/missing text
  .github/workflows/e2e_tests_dev.yaml
  .github/workflows/e2e_tests_staging.yaml
  .github/workflows/e2e_tests_uat.yaml
  .github/workflows/smoke_tests.yaml
  .github/workflows/unit_tests.yaml
  cypress/e2e/DelegatorLifecycleTests.cy.ts
  cypress/e2e/ProtocolParamTests.cy.ts
  cypress/e2e/SmartcontractDetail.cy.ts
  cypress/e2e/contracts.cy.ts
  cypress/e2e/delegationPool.cy.ts
  cypress/e2e/deregistrationScreen/DeregistrationScreenTest.cy.ts
  cypress/e2e/epochs.cy.ts
  cypress/e2e/policy.cy.ts
  cypress/e2e/scenario/ContractScenario/userInteractWithContractTab.cy.ts
  cypress/e2e/spoTabularView/PoolGeneralInformationTest.cy.ts
  cypress/e2e/spoTabularView/SPOTabularViewTest.cy.ts
  cypress/e2e/spoTabularView/TransactionTableTest.cy.ts
  cypress/e2e/stakeKeyTabularView/StakeKeyTabularViewTest.cy.ts
  cypress/e2e/stakingLifecycle/DeregistrationListTest.cy.ts
  cypress/e2e/transactions.cy.ts
  package-lock.json
  package.json
  src/components/CIPComplianceModal/CIP25Modal.tsx
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/pages/DelegatorLifecycle/index.tsx
  src/pages/SPOLifecycle/index.tsx
  yarn.lock
Labels: dev-test

#3278 fix: MET-2051 add missing text tooltip pool name
  src/components/DelegationPool/DelegationList/index.tsx
Labels: 1.1.0

#3283 Feat: met 1957 pool details view
  src/components/GovernanceVotes/index.tsx
Labels: 1.1.0

#3286 feat: MET-1965 update layout
  src/components/Dreps/DrepsOverview/index.tsx
Labels: dev-test

#3287 feat: MET-1965 add missing column
  src/components/Dreps/DrepsList/index.tsx
  src/components/Dreps/DrepsOverview/index.tsx
Labels: dev-test

#3288 feat: MET-1965 update title
  src/locales/en/translation.json
Labels: dev-test

#3289 feat: MET-1958-pools-overview-search-bar
  src/commons/resources/icons/pool-block.svg
  src/commons/resources/icons/pool-name.svg
  src/commons/resources/icons/pool-participation.svg
  src/commons/resources/icons/pool-pledge.svg
  src/commons/resources/icons/pool-saturation.svg
  src/commons/resources/icons/pool-size.svg
  src/commons/resources/icons/pool-voting.svg
  src/commons/resources/index.ts
  src/commons/utils/api.ts
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/DelegationPool/DelegationList/styles.ts
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/CustomFilterMultiRange/styles.ts
  src/locales/en/translation.json
Labels: dev-test

#3291 fix: remove search bar pool overview
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3293 feat: MET-1965 update UI
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/Dreps/DrepsList/index.tsx
  src/components/Dreps/DrepsOverview/index.tsx
Labels: dev-test

#3292 fix: remove search bar pool overview
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3295 feat: MET-1965 update text
  src/components/Dreps/DrepsOverview/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3296 fix: remove search bar test file
  src/components/DelegationPool/DelegationList/DelegationList.test.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/pages/DelegationPools/DelegationPools.test.tsx
Labels: dev-test

#3297 Chore : change color icon
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/CustomFilterMultiRange/styles.ts
Labels: dev-test

#3299 feat: MET-1965 add modal confirm anchor link
  src/components/Dreps/DrepsList/index.tsx
  src/components/Dreps/DrepsOverview/styles.ts
Labels: dev-test

#3300 feat: MET-1965 update status
  src/components/Dreps/DrepsList/index.tsx
Labels: dev-test

#3301 fix: format ada and add condition disable filter
  src/commons/utils/helper.ts
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3302 fix: return wrong data filter
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3303 chore: revert value pool name
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3304 fix: fix range slider and sort when filter
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/DelegationPool/DelegationList/styles.ts
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/CustomFilterMultiRange/styles.ts
Labels: dev-test

#3305 fix: fix logic filter search pools
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3308 Feat/add flag conway era
  docker-compose.yml
  env.global.tmp.js
  src/commons/utils/constants.ts
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/Dreps/index.tsx
  vite.config.ts
Labels: dev-test

#3306 fix: refactor logic filter pool
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3284 feat: MET-1965 add dreps page
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/Dreps/DrepsList/index.tsx
  src/components/Dreps/DrepsList/styles.ts
  src/components/Dreps/DrepsOverview/index.tsx
  src/components/Dreps/DrepsOverview/styles.ts
  src/locales/en/translation.json
  src/pages/Dreps/Dreps.test.tsx
  src/pages/Dreps/index.tsx
  src/pages/Dreps/styles.ts
  src/types/drep.d.ts
Labels: 1.2.0

#3309 Fix/search pool
  src/components/DelegationPool/DelegationList/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3310 Fix/search bar
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3290 feat: MET-1958-pools-overview-search-bar
  src/commons/resources/icons/pool-block.svg
  src/commons/resources/icons/pool-name.svg
  src/commons/resources/icons/pool-participation.svg
  src/commons/resources/icons/pool-pledge.svg
  src/commons/resources/icons/pool-saturation.svg
  src/commons/resources/icons/pool-size.svg
  src/commons/resources/icons/pool-voting.svg
  src/commons/resources/index.ts
  src/commons/utils/api.ts
  src/commons/utils/helper.ts
  src/components/DelegationPool/DelegationList/DelegationList.test.tsx
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/DelegationPool/DelegationList/styles.ts
  src/components/GovernanceVotes/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/CustomFilterMultiRange/styles.ts
  src/locales/en/translation.json
  src/pages/DelegationPools/DelegationPools.test.tsx
Labels: 1.2.0

#3311 Fix/conway flag
  src/components/Dreps/DrepsList/DelegationList.test.tsx
  src/components/Dreps/DrepsOverview/DelegationOverview.test.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/pages/Dreps/Dreps.test.tsx
  src/pages/Dreps/index.tsx
Labels: dev-test

#3307 feat: MET-2061 add flag conway era
  docker-compose.yml
  env.global.tmp.js
  src/commons/utils/constants.ts
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/Dreps/index.tsx
  vite.config.ts
Labels: 1.2.0

#3315 feat: MET-1989 add reponsive
  src/commons/utils/helper.ts
  src/components/Home/LatestStories/LatestStories.test.tsx
  src/components/Home/LatestStories/index.tsx
  src/components/ProtocolHistoryModal/index.tsx
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Header/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/styles.ts
  src/components/commons/Layout/Sidebar/index.tsx
  src/components/commons/Layout/Sidebar/styles.ts
  src/locales/en/translation.json
Labels: dev-test

#3316 feat: MET-1989 update height sidebar
  src/components/commons/Layout/Sidebar/SidebarMenu/styles.ts
Labels: dev-test

#3317 feat: MET-1989 update datetime
  src/commons/utils/helper.ts
  src/components/TransactionLists/index.tsx
  src/components/commons/DatetimeTypeTooltip/index.tsx
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/styles.ts
  src/components/commons/Layout/Sidebar/index.tsx
Labels: dev-test

#3318 fix: fix reset when sort and disable button filter pools
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3319 feat: MET-1989 add hour cycle in format date
  src/commons/utils/helper.ts
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
Labels: dev-test

#3324 fix: MET-1989 update tooltip
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
Labels: dev-test

#3325 feat: MET-1989 update timezone
  src/commons/utils/helper.ts
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Sidebar/index.tsx
Labels: dev-test

#3322 fix: clear params filter pools
  src/components/DelegationPool/DelegationList/index.tsx
Labels: dev-test

#3327 feat: MET-1989 save user tz
  src/commons/utils/api.ts
  src/commons/utils/helper.ts
  src/components/commons/Layout/Header/ConnectWallet/index.tsx
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Sidebar/index.tsx
  src/pages/SignIn/index.tsx
Labels: dev-test

#3326 fix: fix ui button reset filter pools
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3328 feat: MET-1989 update storage
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Sidebar/index.tsx
Labels: dev-test

#3329 fix: change params search to query
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: dev-test

#3330 fix: change params search pool details
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
Labels: dev-test

#3335 Feat/met 1989 setting timezone
  src/commons/utils/helper.ts
  src/components/Account/OverviewTab/OverviewTab.test.tsx
  src/components/StakingLifeCycle/DelegatorLifecycle/ReportComposerModal/StepReviewModal.tsx
  src/components/SystemLoader/index.tsx
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Sidebar/index.tsx
  src/components/commons/OverviewStaking/OverviewStaking.test.tsx
  src/pages/MyProfile/MyProfile.test.tsx
Labels: dev-test

#3337 feat: MET-1989 update format time
  src/commons/utils/helper.ts
Labels: dev-test

#3339 fix: fix filter all params on header filter
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3336 feat: MET-1989 add tz report
  src/commons/utils/helper.ts
  src/components/StakingLifeCycle/DelegatorLifecycle/ReportComposerModal/StepReviewModal.tsx
  src/components/SystemLoader/index.tsx
  src/components/commons/DatetimeTypeTooltip/index.tsx
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Sidebar/index.tsx
  src/components/commons/Layout/index.tsx
Labels: 1.2.0

#3341 feat: MET-1989 update format tz
  src/components/StakeDetail/StakeTab/Tabs/WithdrawalHistoryTab.tsx
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Sidebar/index.tsx
  src/pages/ProtocolParameter/index.tsx
Labels: dev-test

#3340 feat: MET-1989 update format tz
  src/components/StakeDetail/StakeTab/Tabs/WithdrawalHistoryTab.tsx
  src/components/commons/Layout/Header/SettingTimezone/index.tsx
  src/components/commons/Layout/Sidebar/index.tsx
  src/pages/ProtocolParameter/index.tsx
Labels: 1.2.0

#3342 feat: MET-1989 update token expried
  src/commons/utils/axios.ts
  src/commons/utils/constants.ts
Labels: dev-test

#3343 feat: MET-1989 update token expried
  src/commons/utils/axios.ts
  src/commons/utils/constants.ts
Labels: 1.2.0

#3344 feat: MET-1989 update refesh token expried
  src/commons/utils/axios.ts
  src/commons/utils/constants.ts
Labels: dev-test

#3345 feat: MET-1989 update refesh token expried
  src/commons/utils/axios.ts
  src/commons/utils/constants.ts
Labels: 1.2.0

#3334 feat: 2024 Add data-testid to Explorer web elements
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/AddressDetail/AddressHeader/index.tsx
  src/components/AddressTransactionList/index.tsx
  src/components/DelegationDetail/DelegationDetailChart/index.tsx
  src/components/DelegationDetail/DelegationDetailInfo/index.tsx
  src/components/DelegationDetail/DelegationDetailList/index.tsx
  src/components/DelegationDetail/DelegationDetailOverview/index.tsx
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/DelegationPool/DelegationOverview/index.tsx
  src/components/Dreps/DrepsList/index.tsx
  src/components/Dreps/DrepsOverview/index.tsx
  src/components/DynamicEllipsisText/index.tsx
  src/components/EpochDetail/EpochBlockList/index.tsx
  src/components/EpochDetail/EpochOverview/index.tsx
  src/components/GovernanceVotes/index.tsx
  src/components/TopAddresses/ByADABalance/index.tsx
  src/components/TransactionDetail/TransactionMetadata/PoolCertificate/index.tsx
  src/components/TransactionDetail/TransactionMetadata/Summary/index.tsx
  src/components/TransactionDetail/TransactionMetadata/TransactionSignatories/index.tsx
  src/components/TransactionDetail/TransactionMetadata/UTXOs/index.tsx
  src/components/TransactionDetail/TransactionMetadata/index.tsx
  src/components/TransactionDetail/TransactionOverview/index.tsx
  src/components/commons/CardGovernanceVotes/index.tsx
  src/components/commons/ConnectedProfileOptionNormalLogin/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailView/DetailViewEpoch.tsx
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/Epoch/index.tsx
  src/pages/InstantRewards/index.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
  src/pages/NativeScriptsAndSC/TabNativeScripts.tsx
  src/pages/NativeScriptsAndSC/TabSmartContracts.tsx
  src/pages/NativeScriptsAndSC/Tabs.tsx
  src/pages/RegistrationPools/index.tsx
  src/pages/Stake/index.tsx
  src/pages/StakeDelegations/index.tsx
  src/pages/TopAddresses/index.tsx
  src/types/stakeKey.d.ts
Labels: dev-test

#3348 Fix/keep alive ws test
  .github/workflows/release.yaml
  package-lock.json
  package.json
  src/commons/utils/constants.ts
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/SystemLoader/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/Layout/Sidebar/SidebarMenu/index.tsx
  src/pages/DelegationDetail/index.tsx
  src/pages/DrepDetail/index.tsx
  src/pages/Dreps/index.tsx
Labels: dev-test

#3347 Fix/keep alive websocket
  src/components/SystemLoader/index.tsx
Labels: 1.2.0

#3346 fix: clear params filter pools
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/Layout/Header/HeaderSearch/index.tsx
  src/pages/DelegationDetail/DelegationDetail.test.tsx
  src/pages/DelegationDetail/index.tsx
Labels: 1.2.0

#3351 Fix/remove barchart
  src/components/Dreps/DrepsOverview/index.tsx
  src/pages/DelegationDetail/DelegationDetail.test.tsx
  src/pages/DelegationDetail/index.tsx
Labels: dev-test

#3352 fix: MET-1965 update grid
  src/components/Dreps/DrepsOverview/index.tsx
Labels: dev-test

#3353 fix: MET-2109 sort icon break line in table
  src/components/DelegationPool/DelegationList/index.tsx
  src/pages/RegistrationPools/index.tsx
Labels: dev-test

#3354 fix: MET-2109 sort icon break line in table
  src/components/DelegationPool/DelegationList/index.tsx
  src/pages/RegistrationPools/index.tsx
Labels: 1.2.0

#3362 fix: add tz param report
  src/components/StakingLifeCycle/DelegatorLifecycle/ReportComposerModal/StepReviewModal.tsx
Labels: dev-test

#3364 fix: MET 2110 Pools Overview Pools table show Retired pools should mo…
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3365 fix: MET 2018 Pools filter options where there is a bar there should …
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/CustomFilterMultiRange/styles.ts
Labels: dev-test

#3366 fix: add validate input
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3367 fix: set default max value input
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3369 fix: remove convert number
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3371 fix: MET-2108 update format percent filter
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3372 fix: MET 2110 bug ui
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/DelegationPool/DelegationList/styles.ts
  src/components/commons/CustomFilterMultiRange/styles.ts
  src/components/commons/Filter/styles.ts
Labels: dev-test

#3374 fix: MET-2108 update logic filter
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3355 fix: MET 2017 Pools filter options text field not being reset after s…
  src/components/StakingLifeCycle/DelegatorLifecycle/ReportComposerModal/StepReviewModal.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: 1.2.0

#3376 fix: MET-2108 update input
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/CustomFilterMultiRange/styles.ts
Labels: dev-test

#3379 fix: MET-2108 update fixed number
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: dev-test

#3368 Fix/met 2108 pool filter options where there is a bar there should be text input
  src/components/DelegationPool/DelegationList/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
  src/components/commons/CustomFilterMultiRange/styles.ts
Labels: 1.2.0
