Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-10, with the labels that each got.

#3958 fix/met 2049 error server
  src/commons/hooks/useFetchList.ts
Labels: dev-test

#3964 fix: epoch detail bug ui
  playwright/pages/epoch-detail.page.ts
  src/components/EpochDetail/EpochBlockList/index.tsx
Labels: dev-test

#3966 feat: MET-2329 create pre defined votes chart
  src/components/Overview/ChartOverview/index.tsx
  src/components/Overview/ChartPreDefined/index.tsx
  src/components/Overview/ChartPreDefined/styles.ts
  src/components/Overview/TabOverview/styles.ts
  src/components/Overview/index.tsx
  src/locales/en/translation.json
Labels: dev-test

#3961 fix: css in site test
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: dev-test

#3969 Fix/pagination associated addresses test
  src/pages/SmartContractDetail/TabAssociated.tsx
Labels: dev-test

#3971 fix: token bug ui
  src/components/CIPComplianceModal/styles.ts
  src/components/commons/CustomModal/styles.ts
Labels: dev-test

#3972 feat: MET-2346 replace card
  src/commons/resources/icons/pots-icon-dark.svg
  src/commons/resources/icons/pots-icon.svg
  src/commons/resources/index.ts
  src/commons/utils/api.ts
  src/commons/utils/helper.ts
  src/components/Home/Statistic/index.tsx
  src/components/Home/Statistic/style.ts
  src/locales/en/translation.json
  src/types/stakeKey.d.ts
Labels: dev-test

#3974 fix: token crashed
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TransactionListsFull/index.tsx
Labels: dev-test

#3976 Feat/met 2360 remove column from transaction table view test
  playwright/pages/block-detail.page.ts
  src/components/TransactionListsFull/index.tsx
Labels: dev-test

#3977 fix: remove column token detail page
  playwright/pages/native-token.page.ts
  playwright/tests/e2e/steps/native-token.steps.ts
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
Labels: dev-test

#3979 Fix/pagination associated addresses
  src/components/DynamicEllipsisText/index.tsx
  src/components/commons/Table/index.tsx
  src/components/commons/Table/styles.ts
Labels: dev-test

#3938 feat: MET-2366 Remove top token holders
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
  src/pages/TokenDetail/index.tsx
Labels: 1.10.0

#3940 feat: MET-2350 Remove column from block table
  src/pages/BlockList/index.tsx
Labels: 1.10.0

#3942 feat: Remove column from epoch table
  src/pages/Epoch/index.tsx
Labels: 1.10.0

#3960 fix: MET-2049-error-server
  src/commons/hooks/useFetchList.ts
Labels: 1.10.0

#3946 Fix/input zero stake
  src/components/Dreps/DrepFilter/index.tsx
  src/components/GovernanceActionDetails/VotesOverview/FilterVotesOverview/index.tsx
  src/components/commons/CustomFilterMultiRange/index.tsx
Labels: 1.10.0

#3941 feat: MET-2361 Remove unneeded tiles from token detail page
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
  src/pages/TokenDetail/index.tsx
Labels: 1.10.0

#3981 fix: MET-2364 Get bolnisi numbers from API backend
  src/commons/utils/api.ts
  src/pages/BolnisiLanding/index.tsx
Labels: 1.9.0

#3965 fix: epoch detail bug ui
  playwright/pages/epoch-detail.page.ts
  src/components/EpochDetail/EpochBlockList/index.tsx
Labels: 1.10.0

#3980 feat: MET-2356 Remove column from token table
  playwright/pages/native-token.page.ts
  src/components/commons/DetailView/DetailViewToken.tsx
  src/pages/Token/index.tsx
Labels: 1.10.0

#3982 fix/met 2346 replace card dashboard page
  src/components/Home/Statistic/index.tsx
Labels: dev-test

#3984 feat: MET-2348 remove column from epoch table
  playwright/pages/epochs-dashboard.page.ts
  src/components/commons/DetailView/DetailViewEpoch.tsx
Labels: dev-test

#3988 fix: bug ui pagination
  src/components/commons/Table/index.tsx
  src/components/commons/Table/styles.ts
Labels: dev-test

#3936 Feat/met 2360 remove column from transaction table view
  playwright/pages/block-detail.page.ts
  playwright/pages/blocks-dashboard.page.ts
  playwright/pages/epochs-dashboard.page.ts
  playwright/pages/transaction-overview.page.ts
  src/components/TransactionLists/index.tsx
  src/components/TransactionListsFull/index.tsx
Labels: 1.10.0

#3944 Remove/met 2344 ada holder page
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/api/dtos/topADAHolders.dto.ts
  playwright/helpers/endpoints.ts
  playwright/pages/top-ADA-holders.page.ts
  playwright/tests/e2e/features/top-ADA-holders.feature
  playwright/tests/e2e/steps/top-ADA-holders.step.ts
  src/Routers.tsx
  src/commons/menus.ts
  src/commons/routers.ts
  src/commons/utils/api.ts
  src/components/TopAddresses/ByADABalance/TopAddressesByADABalance.test.tsx
  src/components/TopAddresses/ByADABalance/index.tsx
  src/components/TopAddresses/ByADABalance/styles.ts
  src/pages/TopAddresses/TopAddresses.test.tsx
  src/pages/TopAddresses/index.tsx
  src/pages/TopAddresses/styles.ts
Labels: 1.10.0

#3945 fix: MET-2370 change text
  src/locales/en/translation.json
  src/pages/Micar/styles.ts
Labels: 1.10.0

#3967 dfix: pagination associated address
  src/components/DynamicEllipsisText/index.tsx
  src/components/commons/Table/index.tsx
  src/pages/SmartContractDetail/TabAssociated.tsx
Labels: 1.10.0

#3973 feat: MET-2329 create pre defined votes chart
  src/components/Overview/ChartOverview/index.tsx
  src/components/Overview/ChartPreDefined/index.tsx
  src/components/Overview/ChartPreDefined/styles.ts
  src/components/Overview/TabOverview/styles.ts
  src/components/Overview/index.tsx
  src/locales/en/translation.json
Labels: 1.10.0

#3983 feat: MET-2348 remove column from epoch table
  playwright/pages/epochs-dashboard.page.ts
  src/components/commons/DetailView/DetailViewEpoch.tsx
Labels: 1.10.0

#3985 fix: micar history chart bug ui
  src/pages/Micar/MicarChart/index.tsx
Labels: 1.10.0

#3989 feat/met 2346 replace card dashboard page
  src/commons/resources/icons/pots-icon-dark.svg
  src/commons/resources/icons/pots-icon.svg
  src/commons/resources/index.ts
  src/commons/utils/api.ts
  src/commons/utils/helper.ts
  src/components/Home/Statistic/index.tsx
  src/components/Home/Statistic/style.ts
  src/locales/en/translation.json
  src/types/stakeKey.d.ts
Labels: 1.10.0

#3994 fix/UI token detail
  src/components/StakeDetail/StakeAnalytics/styles.ts
  src/components/TokenDetail/TokenAnalytics/index.tsx
  src/pages/NativeScriptsAndSC/Card.tsx
Labels: dev-test

#3951 fix: token bug ui
  playwright/pages/native-token.page.ts
  playwright/tests/e2e/steps/native-token.steps.ts
  src/components/CIPComplianceModal/styles.ts
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/commons/CustomModal/styles.ts
  src/components/commons/DetailHeader/styles.ts
  src/pages/Token/index.tsx
Labels: 1.10.0

#3995 test: fix unit test
  .github/workflows/release.yaml
  package.json
  src/commons/hooks/useFetch.test.ts
  src/commons/hooks/useFetchList.ts
  src/components/EpochDetail/EpochBlockList/EpochBlockList.test.tsx
  src/components/Home/Trending/TransactionChart/TransactionChart.test.tsx
  src/components/StakingLifeCycleSearch/StackingLifeCycleSearch.test.tsx
  src/components/TokenDetail/TokenOverview/TokenOverview.test.tsx
  src/components/TransactionDetail/TransactionMetadata/Summary/Summary.test.tsx
  src/components/TransactionDetail/TransactionMetadata/TransactionMetadata.test.tsx
  src/components/commons/DetailView/DetailViewEpoch.test.tsx
  src/components/commons/DetailView/DetailViewToken.test.tsx
  src/components/commons/Layout/Layout.test.tsx
  src/pages/ProtocolParameter/ProtocolParameter.test.tsx
  src/pages/StakeDetail/StakeDetail.test.tsx
  src/pages/TokenDetail/TokenDetail.test.tsx
  src/pages/TransactionDetail/TransactionDetail.test.tsx
  src/types/transactions.d.ts
Labels: 1.10.0

#3998 Fix/common bug UI mobile
  .github/workflows/release.yaml
  package.json
  src/commons/hooks/useFetch.test.ts
  src/commons/hooks/useFetchList.ts
  src/components/EpochDetail/EpochBlockList/EpochBlockList.test.tsx
  src/components/Home/Trending/TransactionChart/TransactionChart.test.tsx
  src/components/StakingLifeCycleSearch/StackingLifeCycleSearch.test.tsx
  src/components/TokenDetail/TokenOverview/TokenOverview.test.tsx
  src/components/TransactionDetail/TransactionMetadata/Summary/Summary.test.tsx
  src/components/TransactionDetail/TransactionMetadata/TransactionMetadata.test.tsx
  src/components/commons/DetailHeader/styles.ts
  src/components/commons/DetailView/DetailViewEpoch.test.tsx
  src/components/commons/DetailView/DetailViewToken.test.tsx
  src/components/commons/Layout/Layout.test.tsx
  src/pages/ProtocolParameter/ProtocolParameter.test.tsx
  src/pages/StakeDetail/StakeDetail.test.tsx
  src/pages/TokenDetail/TokenDetail.test.tsx
  src/pages/TransactionDetail/TransactionDetail.test.tsx
  src/types/transactions.d.ts
Labels: dev-test

#3999 sync main to 1.8.0
  CHANGELOG.md
  playwright.config.ts
  playwright/api/call-blockfrost/blockfrost.api.ts
  playwright/api/call-koios/koios.api.ts
  playwright/api/dtos/blockfrostNativeTokenInformation.dto.ts
  playwright/api/dtos/topADAHolders.dto.ts
  playwright/helpers/endpoints.ts
  playwright/pages/native-token.page.ts
  playwright/pages/script-detail.page.ts
  playwright/pages/token-detail.page.ts
  playwright/pages/top-ADA-holders.page.ts
  playwright/tests/e2e/features/native-token.feature
  playwright/tests/e2e/features/top-ADA-holders.feature
  playwright/tests/e2e/steps/native-token.steps.ts
  playwright/tests/e2e/steps/top-ADA-holders.step.ts
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenTableData/TokenTopHolder.tsx
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TokenDetail/TokenTableData/index.tsx
  src/components/TopAddresses/ByADABalance/index.tsx
  src/components/TopAddresses/ByAmountStaked/index.tsx
  src/components/commons/DetailView/DetailViewToken.tsx
  src/pages/Token/index.tsx
Labels: 1.8.0

#4000 sync main with 1.9.0
  playwright.config.ts
  playwright/tests/e2e/features/native-token.feature
Labels: 1.9.0

#4001 sync main with 1.10.0
  playwright.config.ts
  playwright/tests/e2e/features/native-token.feature
Labels: 1.10.0

#4002 fix: bug ui common
  src/components/DynamicEllipsisText/index.tsx
Labels: dev-test

#4008 Fix/overlap highest lowest value
  playwright.config.ts
  playwright/tests/e2e/features/native-token.feature
  src/components/AddressDetail/AddressAnalytics/index.tsx
Labels: dev-test

#4011 Fix/met 2375 bolnisi filter button
  src/components/TokenDetail/TokenTableData/TokenTableData.test.tsx
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#4010 fix: MET-2375 update select option in bolnisi page
  src/pages/BolnisiLanding/index.tsx
Labels: 1.10.0

#4013 fix: overlap value
  src/components/AddressDetail/AddressAnalytics/index.tsx
Labels: dev-test

#4014 fix: revert code devtest
  src/components/commons/DetailHeader/styles.ts
Labels: dev-test

#3962 fix/css in site test
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/DelegationDetail/DelegationDetailChart/index.tsx
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: 1.10.0

#4020 fix: Remove side bar from transactions table page
  playwright/pages/transaction-overview.page.ts
  playwright/tests/e2e/steps/transactions-overview.steps.ts
  src/components/TransactionLists/index.tsx
  src/components/commons/DetailView/DetailViewTransaction.test.tsx
  src/components/commons/DetailView/DetailViewTransaction.tsx
  src/pages/TransactionList/index.tsx
Labels: dev-test

#3997 fix: common bug ui mobile
  src/components/DynamicEllipsisText/index.tsx
  src/components/TransactionDetail/TransactionMetadata/Collaterals/index.tsx
  src/components/TransactionDetail/TransactionMetadata/Withdrawals/index.tsx
  src/components/commons/DetailHeader/styles.ts
  src/pages/SmartContractDetail/TabAssociated.tsx
Labels: 1.10.0

#4024 fix: Remove side bar from native tokens page
  src/components/commons/DetailView/DetailViewToken.test.tsx
  src/components/commons/DetailView/DetailViewToken.tsx
  src/pages/Token/index.tsx
Labels: dev-test

#4027 fix: MET-2351 Remove side bar from block view
  playwright/pages/blocks-dashboard.page.ts
  playwright/tests/e2e/steps/blocks.steps.ts
  src/components/commons/DetailView/DetailViewBlock.test.tsx
  src/components/commons/DetailView/DetailViewBlock.tsx
  src/components/commons/Table/index.tsx
  src/pages/BlockList/index.tsx
  src/types/table.d.ts
Labels: dev-test

#4039 Feat/met 2352 dev test make epoch table row expandable
  src/components/AddressTransactionList/index.tsx
  src/components/StakeDetail/StakeTab/Tabs/DelegationHistoryTab.tsx
  src/components/TransactionLists/index.tsx
  src/components/commons/Table/index.tsx
  src/components/commons/Table/styles.ts
  src/pages/Epoch/index.tsx
  src/pages/Epoch/styles.ts
  src/pages/TransactionList/TransactionList.test.tsx
  src/types/table.d.ts
Labels: dev-test

#4043 Feat/met 2352 dev test make epoch table row expandable
  src/components/commons/Table/index.tsx
  src/components/commons/Table/styles.ts
Labels: dev-test

#4045 feat: MET-2384 Remove txcount from token overview
  playwright/pages/native-token.page.ts
  src/components/TokenDetail/TokenOverview/index.tsx
  src/pages/Token/index.tsx
Labels: dev-test

#4048 feat: MET-2376 remove info icons governanve vote
  src/components/GovernanceVotes/OverallVote.tsx
Labels: dev-test

#4050 Feat/met 2352 make epoch table row expandable
  src/components/commons/Table/index.tsx
  src/pages/Epoch/styles.ts
Labels: dev-test

#4052 fix: transaction detail bug ui
  src/components/Contracts/UPLCTree/styles.tsx
Labels: dev-test

#4053 feat: MET-2355 add info when hover text
  src/components/BlockDetail/BlockOverview/index.tsx
  src/components/TransactionDetail/TransactionOverview/index.tsx
  src/components/TransactionLists/index.tsx
  src/locales/en/translation.json
  src/pages/BlockList/index.tsx
Labels: dev-test

#4055 feat: MET-2382 add usecase in bolnisi page
  src/pages/BolnisiLanding/index.tsx
Labels: dev-test

#4056 feat: MET-2382 add usecase in bolnisi page
  src/pages/BolnisiLanding/index.tsx
Labels: 2.0.0

#4057 Feat/met 2352 t make epoch table row expandable
  src/components/commons/Table/index.tsx
  src/pages/BlockList/index.tsx
  src/pages/Epoch/index.tsx
  src/types/table.d.ts
Labels: dev-test

#4025 fix: Remove side bar from native tokens page
  src/components/commons/DetailView/DetailViewToken.test.tsx
  src/components/commons/DetailView/DetailViewToken.tsx
  src/pages/Token/index.tsx
Labels: 2.0.0

#4019 fix: Remove holders from native scripts overview page
  src/pages/NativeScriptsAndSC/Card.tsx
  src/pages/NativeScriptsAndSC/TabNativeScripts.tsx
  src/types/scripts.d.ts
Labels: 2.0.0

#4021 fix: Remove side bar from transactions table page
  playwright/pages/transaction-overview.page.ts
  playwright/tests/e2e/steps/transactions-overview.steps.ts
  src/components/TransactionLists/index.tsx
  src/components/commons/DetailView/DetailViewTransaction.test.tsx
  src/components/commons/DetailView/DetailViewTransaction.tsx
  src/pages/TransactionList/index.tsx
Labels: 2.0.0

#4058 fix: update coding
  src/components/TransactionLists/index.tsx
  src/pages/BlockList/index.tsx
Labels: dev-test

#4064 fix: UI slot absolute slot
  src/components/TransactionDetail/TransactionOverview/index.tsx
Labels: dev-test

#4065 feat: add tooltip in epoch detail
  src/components/EpochDetail/EpochBlockList/index.tsx
Labels: dev-test

#4066 Feat/met 2352 t make epoch table row expandable
  src/components/commons/Epoch/FirstEpoch/index.tsx
  src/pages/Epoch/index.tsx
Labels: dev-test

#4067 fix: bug ui in small screen
  src/components/commons/DetailHeader/styles.ts
Labels: dev-test

#4026 fix: MET-2351 Remove side bar from block view
  playwright/pages/blocks-dashboard.page.ts
  playwright/tests/e2e/steps/blocks.steps.ts
  src/components/commons/DetailView/DetailViewBlock.test.tsx
  src/components/commons/DetailView/DetailViewBlock.tsx
  src/components/commons/Table/index.tsx
  src/pages/BlockList/index.tsx
  src/types/table.d.ts
Labels: 2.0.0

#4068 Feat/met 2355 add info hover text
  src/components/BlockDetail/BlockOverview/index.tsx
  src/components/EpochDetail/EpochBlockList/index.tsx
  src/components/TransactionDetail/TransactionOverview/index.tsx
  src/components/TransactionLists/index.tsx
  src/locales/en/translation.json
  src/pages/BlockList/index.tsx
Labels: 2.0.0

#4051 fix: transaction detail bug ui
  src/components/Contracts/UPLCTree/styles.tsx
Labels: 2.0.0

#4059 fix: Delete icon tooltip gorvernanve vote
  src/components/GovernanceVotes/OverviewVote.tsx
Labels: 2.0.0

#4069 Remove/met 2347 right menu epoch
  src/components/commons/DetailView/DetailViewEpoch.test.tsx
  src/components/commons/DetailView/DetailViewEpoch.tsx
  src/pages/Epoch/index.tsx
Labels: 2.0.0

#4047 feat: MET-2376 remove info icons governanve vote
  src/components/GovernanceVotes/OverallVote.tsx
Labels: 2.0.0

#4070 feat: add tooltip slot and absolute slot
  src/components/AddressTransactionList/index.tsx
  src/components/StakeDetail/StakeTab/Tabs/TransactionTab.tsx
Labels: dev-test

#4072 Fix/overlap highest lowest value
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: dev-test

#4073 Fix/drep details bug UI
  src/pages/DrepDetail/index.tsx
Labels: hold, 2.0.0

#4074 Fix/drep details bug UI test
  src/pages/DrepDetail/index.tsx
Labels: dev-test

#4075 feat: add info hover slot and absolute slot
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
Labels: dev-test

#4077 fix: still loading when data return in dashboard page
  src/components/Home/Statistic/index.tsx
Labels: dev-test

#4079 Fix/ token detail bug UI
  src/components/TokenDetail/TokenOverview/index.tsx
Labels: dev-test

#4082 fix: overlap value lowest and highest
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: dev-test

#4080 fix: token detail bug ui
  src/components/TokenDetail/TokenOverview/index.tsx
Labels: 1.11.0

#4078 fix: still loading when data return in dashboard page
  src/components/Home/Statistic/index.tsx
Labels: 1.11.0

#4076 feat: add info hover slot and absolute slot
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
Labels: 1.11.0

#4085 Feat/met 2354 t make block table row expandable
  .github/workflows/release.yaml
  CHANGELOG.md
  package.json
  src/commons/menus.ts
  src/components/commons/Table/index.tsx
  src/locales/en/translation.json
  src/pages/BlockList/index.tsx
  src/pages/BolnisiLanding/index.tsx
  src/pages/Epoch/index.tsx
  src/pages/Micar/index.tsx
  src/types/table.d.ts
Labels: dev-test

#4086 fix: overlap value in chart
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: dev-test

#4061 Feat/met 2354 make block table row expandable
  src/components/commons/Table/index.tsx
  src/pages/BlockList/index.tsx
  src/pages/Epoch/index.tsx
  src/types/table.d.ts
Labels: 1.11.0

#4087 fix: overlap value chart
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: dev-test
