Repository cardano-foundation/cf-explorer-frontend, pull requests merged in 2024-11, with the labels that each got.

#4009 Fix/overlap highest lowest value
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: 1.10.0

#4089 Fix/overlap highest lowest value
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: 1.11.0

#4090 merge 1.11.0 into main
  src/components/AddressDetail/AddressAnalytics/index.tsx
  src/components/StakeDetail/StakeAnalytics/index.tsx
Labels: 1.11.0

#4091 feat: MET-2397 Navigate transaction overview epoch
  src/components/EpochDetail/EpochBlockList/index.tsx
  src/components/StakeDetail/StakeTab/Tabs/TransactionTab.tsx
  src/components/TokenDetail/TokenTableData/TokenTransaction.tsx
  src/components/TransactionLists/index.tsx
Labels: 1.11.0

#4101 fix: MET-2396 News and Block" link under "Discover Cardano"
  src/commons/menus.ts
  src/locales/en/translation.json
Labels: dev-test

#4103 fix: color text darkmode
  src/components/commons/DetailHeader/index.tsx
Labels: dev-test

#4107 fix: Gorvernance action bug ui
  src/components/GovernanceActionDetails/Description/styles.ts
Labels: dev-test

#4104 fix: Token detail bug ui
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/commons/DetailHeader/index.tsx
  src/components/commons/DetailHeader/styles.ts
Labels: dev-test

#4109 feat: MET-2390 Remove token icons and show them with nsfw button
  package-lock.json
  package.json
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenOverview/styles.ts
  src/locales/en/translation.json
  src/pages/Token/index.tsx
Labels: dev-test

#4094 fix: MET-2393 Adjust context paths of bolnisi and micar
  src/commons/routers.ts
Labels: 1.12.0

#4108 fix: Gorvernance action bug ui
  src/components/GovernanceActionDetails/Description/styles.ts
Labels: 1.12.0

#4114 fix: MET-2401 refactor source code
  src/commons/resources/icons/DelegatingIcon.svg
  src/commons/resources/icons/DisclaimerIcon.svg
  src/commons/resources/icons/DrepId.svg
  src/commons/resources/icons/EmptyIconDark.svg
  src/commons/resources/icons/ada-price-dark.svg
  src/commons/resources/icons/ada-price.svg
  src/commons/resources/icons/avatar-icon.svg
  src/commons/resources/icons/cardano-system-dark.svg
  src/commons/resources/icons/cardano-system.svg
  src/commons/resources/icons/cardanoBlue.svg
  src/commons/resources/icons/cardanoBlueDarkmode.svg
  src/commons/resources/icons/certificate-dark.svg
  src/commons/resources/icons/certificate.svg
  src/commons/resources/icons/coming-soon.svg
  src/commons/resources/icons/community-icon-dark.svg
  src/commons/resources/icons/community-icon-light.svg
  src/commons/resources/icons/complied-cip25.svg
  src/commons/resources/icons/copy-outline-2.svg
  src/commons/resources/icons/copy.svg
  src/commons/resources/icons/createdrep.svg
  src/commons/resources/icons/cube.svg
  src/commons/resources/icons/curent-epoch-pool-dark.svg
  src/commons/resources/icons/curent-epoch-pool.svg
  src/commons/resources/icons/curent-epoch.svg
  src/commons/resources/icons/current-status.svg
  src/commons/resources/icons/delegationHistory.svg
  src/commons/resources/icons/delegationHistoryGreen.svg
  src/commons/resources/icons/delegationIcon.svg
  src/commons/resources/icons/delegator.svg
  src/commons/resources/icons/deregistration-icon-dark.svg
  src/commons/resources/icons/deregistration-icon-light.svg
  src/commons/resources/icons/drop.svg
  src/commons/resources/icons/eternl.svg
  src/commons/resources/icons/explorer-logo.svg
  src/commons/resources/icons/fetch-data-err-dark.svg
  src/commons/resources/icons/fetch-data-err-light.svg
  src/commons/resources/icons/flint.svg
  src/commons/resources/icons/footer-bg.svg
  src/commons/resources/icons/logo-darkmode.svg
  src/commons/resources/icons/logo.svg
  src/commons/resources/icons/nami.svg
  src/commons/resources/icons/noData.svg
  src/commons/resources/icons/short-logo-darkmode.svg
  src/commons/resources/icons/traceabilityImageDefault.png
  src/commons/resources/icons/typhon.svg
  src/commons/resources/icons/yoroi.svg
  src/logo.svg
Labels: 1.12.0

#4110 feat: MET-2390 Remove token icons and show them with nsfw button
  package-lock.json
  package.json
  src/components/TokenDetail/TokenOverview/index.tsx
  src/components/TokenDetail/TokenOverview/styles.ts
  src/locales/en/translation.json
  src/pages/Token/index.tsx
Labels: 1.12.0

#4111 Met 2402 create automation tests for bolnisi and mi car
  .github/workflows/playwright_e2e_tests_uat.yaml
  package-lock.json
  playwright/api/call-mica/mica.api.ts
  playwright/api/call-mica/mica.service.ts
  playwright/api/dtos/cardanoMicaIndicatorsDto.ts
  playwright/api/dtos/micaIndicator.dto.ts
  playwright/helpers/endpoints.ts
  playwright/helpers/methods.ts
  playwright/pages/block-detail.page.ts
  playwright/pages/blocks-dashboard.page.ts
  playwright/pages/epoch-detail.page.ts
  playwright/pages/stake-delegation.page.ts
  playwright/pages/stake-detail.page.ts
  playwright/pages/sustainability.page.ts
  playwright/pages/traceability.page.ts
  playwright/tests/e2e/features/blocks.feature
  playwright/tests/e2e/features/sustainability.feature
  playwright/tests/e2e/features/traceability.feature
  playwright/tests/e2e/features/transaction-overview.feature
  playwright/tests/e2e/steps/blocks.steps.ts
  playwright/tests/e2e/steps/sustainability.steps.ts
  playwright/tests/e2e/steps/traceability.steps.ts
Labels: Automation Test
